# Ruta: core/config/enterprise/trading.yaml
# trading.yaml - Configuración principal de trading enterprise
# Ubicación: C:\TradingBot_v10\config\enterprise\trading.yaml

version: "1.0"
environment: "development"  # development, paper_trading, live_trading

# Configuración global de trading
trading:
  # Modo de operación
  mode: "paper_trading"  # paper_trading, live_trading
  
  # Exchange configuration
  exchange:
    name: "bitget"
    type: "futures"  # spot, futures, both
    
  # Símbolos a tradear
  symbols:
    primary:
      - symbol: "BTCUSDT"
        enabled: true
        priority: 1
        max_position_size_usd: 5000
        min_position_size_usd: 100
        
      - symbol: "ETHUSDT"
        enabled: true
        priority: 1
        max_position_size_usd: 3000
        min_position_size_usd: 75
        
      - symbol: "ADAUSDT"
        enabled: true
        priority: 2
        max_position_size_usd: 2000
        min_position_size_usd: 50
        
      - symbol: "SOLUSDT"
        enabled: true
        priority: 2
        max_position_size_usd: 2000
        min_position_size_usd: 50
        
      - symbol: "DOGEUSDT"
        enabled: true
        priority: 3
        max_position_size_usd: 1000
        min_position_size_usd: 25
    
    # Configuración por defecto para símbolos secundarios
    default_config:
      enabled: false
      priority: 3
      max_position_size_usd: 500
      min_position_size_usd: 25

# Configuración de futuros
futures:
  # Configuración de leverage
  leverage:
    # Leverage dinámico basado en confianza del modelo
    dynamic_leverage:
      enabled: true
      base_leverage: 5
      max_leverage: 30
      min_leverage: 2
      
      # Multiplicadores basados en confianza
      confidence_multipliers:
        high_confidence: 2.0    # >90% confianza
        medium_confidence: 1.5  # 70-90% confianza
        low_confidence: 1.0     # 50-70% confianza
        very_low_confidence: 0.5 # <50% confianza
        
    # Leverage fijo por símbolo (alternativo)
    fixed_leverage:
      enabled: false
      leverage_by_symbol:
        BTCUSDT: 10
        ETHUSDT: 8
        ADAUSDT: 5
        SOLUSDT: 5
        DOGEUSDT: 3
        
  # Configuración de posiciones
  positions:
    # Tipos de posición permitidos
    allowed_sides: ["long", "short", "both"]  # long, short, both
    
    # Configuración de margin
    margin_mode: "isolated"  # isolated, cross
    
    # Duración máxima de posiciones
    max_position_duration_hours: 168  # 7 días
    
    # Configuración de hedging
    hedging:
      enabled: false
      max_hedge_ratio: 0.5

# Configuración de estrategias
strategies:
  # Estrategia principal ML
  ml_strategy:
    enabled: true
    weight: 0.7  # 70% del capital asignado
    
    # Configuración del modelo
    model:
      name: "lstm_attention"
      confidence_threshold: 0.65
      prediction_horizon_minutes: 60
      
    # Configuración de señales
    signals:
      min_confidence: 0.65
      signal_aggregation: "weighted_average"
      signal_timeout_minutes: 30
      
  # Estrategia momentum
  momentum_strategy:
    enabled: true
    weight: 0.2  # 20% del capital
    
    indicators:
      rsi_period: 14
      rsi_overbought: 70
      rsi_oversold: 30
      macd_fast: 12
      macd_slow: 26
      macd_signal: 9
      
  # Estrategia mean reversion
  mean_reversion_strategy:
    enabled: true
    weight: 0.1  # 10% del capital
    
    indicators:
      bollinger_period: 20
      bollinger_std: 2
      mean_reversion_threshold: 0.02

# Configuración de órdenes
orders:
  # Tipos de orden permitidos
  allowed_order_types: ["market", "limit", "stop", "stop_limit"]
  
  # Configuración por tipo de orden
  market_orders:
    enabled: true
    max_slippage_percent: 0.1
    timeout_seconds: 30
    
  limit_orders:
    enabled: true
    price_offset_percent: 0.05  # 0.05% mejor que precio actual
    timeout_minutes: 60
    
  stop_orders:
    enabled: true
    trailing_stop: true
    
  # Configuración de ejecución
  execution:
    max_order_size_usd: 10000
    min_order_size_usd: 10
    order_batching: true
    batch_size: 5
    batch_timeout_seconds: 10

# Configuración de timing
timing:
  # Frecuencia de análisis
  analysis_frequency_seconds: 30
  
  # Frecuencia de rebalanceo
  rebalance_frequency_minutes: 60
  
  # Horarios de trading
  trading_hours:
    enabled: false  # true para limitar horarios
    timezone: "UTC"
    start_time: "00:00"
    end_time: "23:59"
    
    # Días de la semana (0=Lunes, 6=Domingo)
    trading_days: [0, 1, 2, 3, 4, 5, 6]
    
    # Pausas (ej. durante noticias importantes)
    breaks:
      - start: "12:00"
        end: "12:30"
        reason: "daily_rebalance"

# Configuración de performance
performance:
  # Targets de rendimiento
  targets:
    daily_return_target: 0.02     # 2% diario
    weekly_return_target: 0.10    # 10% semanal
    monthly_return_target: 0.25   # 25% mensual
    max_drawdown_target: 0.15     # 15% máximo drawdown
    
  # Métricas de seguimiento
  tracking_metrics:
    - "total_return"
    - "sharpe_ratio"
    - "sortino_ratio"
    - "max_drawdown"
    - "win_rate"
    - "profit_factor"
    - "calmar_ratio"
    - "var_95"
    - "cvar_95"

# Configuración de monitoreo
monitoring:
  # Métricas en tiempo real
  real_time_metrics:
    enabled: true
    update_frequency_seconds: 5
    
    metrics:
      - "account_balance"
      - "unrealized_pnl"
      - "realized_pnl"
      - "open_positions_count"
      - "daily_return"
      - "portfolio_value"
      - "leverage_ratio"
      - "margin_usage"
      
  # Alertas
  alerts:
    enabled: true
    
    # Canales de notificación
    channels:
      slack:
        enabled: true
        webhook_url: ""  # Configurar en vault
        channel: "#trading-alerts"
        
      email:
        enabled: false
        recipients: ["trader@company.com"]
        
      discord:
        enabled: false
        webhook_url: ""
        
    # Condiciones de alerta
    conditions:
      - name: "high_drawdown"
        condition: "current_drawdown > 0.10"
        severity: "critical"
        message: "Drawdown alto detectado: {value}%"
        
      - name: "large_loss"
        condition: "daily_pnl < -500"
        severity: "warning"
        message: "Pérdida diaria grande: ${value}"
        
      - name: "margin_call_risk"
        condition: "margin_ratio > 0.8"
        severity: "critical"
        message: "Riesgo de margin call: {value}%"
        
      - name: "unexpected_position"
        condition: "position_count > max_positions"
        severity: "warning"
        message: "Número de posiciones excede límite"

# Configuración de prometheus
prometheus:
  enabled: true
  port: 8003
  metrics_prefix: "trading"
  
  # Métricas específicas
  custom_metrics:
    - name: "trades_executed_total"
      type: "counter"
      labels: ["symbol", "side", "status"]
      
    - name: "account_balance_usd"
      type: "gauge"
      
    - name: "open_positions_count"
      type: "gauge"
      labels: ["symbol", "side"]
      
    - name: "trade_pnl_usd"
      type: "histogram"
      labels: ["symbol", "side"]
      buckets: [-1000, -500, -100, -50, -10, 0, 10, 50, 100, 500, 1000]

# Configuración de backtesting
backtesting:
  enabled: true
  
  # Configuración de datos
  data:
    start_date: "2023-01-01"
    end_date: "2024-12-31"
    timeframe: "1h"
    
  # Configuración de costos
  costs:
    commission_rate: 0.0006  # 0.06% por trade
    slippage_rate: 0.0001    # 0.01% slippage promedio
    funding_rate: 0.0001     # 0.01% funding rate promedio
    
  # Configuración de capital inicial
  initial_capital: 10000
  
  # Métricas a calcular
  metrics:
    - "total_return"
    - "annualized_return"
    - "volatility"
    - "sharpe_ratio"
    - "sortino_ratio"
    - "max_drawdown"
    - "calmar_ratio"
    - "win_rate"
    - "profit_factor"
    - "average_trade_duration"
    - "var_95"
    - "cvar_95"

# Configuración de logging
logging:
  level: "INFO"
  
  # Archivos de log específicos
  files:
    trading_main:
      path: "logs/enterprise/trading/main.log"
      max_size_mb: 100
      backup_count: 10
      
    orders:
      path: "logs/enterprise/trading/orders.log"
      max_size_mb: 50
      backup_count: 20
      
    positions:
      path: "logs/enterprise/trading/positions.log"
      max_size_mb: 50
      backup_count: 20
      
    risk:
      path: "logs/enterprise/trading/risk.log"
      max_size_mb: 25
      backup_count: 30
      
    performance:
      path: "logs/enterprise/trading/performance.log"
      max_size_mb: 25
      backup_count: 30
      
  # Formato de logs
  formatters:
    trading: "%(asctime)s - %(name)s - %(levelname)s - [%(symbol)s] - %(message)s"
    risk: "%(asctime)s - RISK - %(levelname)s - %(message)s"
    compliance: "%(asctime)s - COMPLIANCE - %(levelname)s - %(message)s"

# Configuración de desarrollo vs producción
environment_configs:
  development:
    mode: "paper_trading"
    max_position_size_usd: 100
    max_daily_loss_usd: 50
    leverage_multiplier: 0.5
    
  paper_trading:
    mode: "paper_trading"
    max_position_size_usd: 1000
    max_daily_loss_usd: 200
    leverage_multiplier: 0.8
    
  live_trading:
    mode: "live_trading"
    max_position_size_usd: 5000
    max_daily_loss_usd: 500
    leverage_multiplier: 1.0
    
    # Configuraciones adicionales de seguridad para live
    safety_checks:
      double_confirm_orders: true
      max_orders_per_minute: 10
      circuit_breaker_enabled: true
