# trading_bot_rules.yml - Reglas de alertas para Trading Bot
# Ubicación: C:\TradingBot_v10\monitoring\prometheus\rules\trading_bot_rules.yml

groups:
  - name: trading_bot_critical
    rules:
      # Alertas críticas del sistema
      - alert: TradingBotDown
        expr: up{job="trading-bot-main"} == 0
        for: 1m
        labels:
          severity: critical
          service: trading-bot
        annotations:
          summary: "Trading Bot principal está caído"
          description: "El servicio principal del Trading Bot no responde desde hace {{ $value }} minutos"
          runbook_url: "https://docs.trading-bot.com/runbooks/trading-bot-down"

      - alert: DatabaseDown
        expr: up{job="timescaledb"} == 0
        for: 30s
        labels:
          severity: critical
          service: database
        annotations:
          summary: "Base de datos TimescaleDB no responde"
          description: "La base de datos TimescaleDB no está disponible"
          runbook_url: "https://docs.trading-bot.com/runbooks/database-down"

      - alert: KafkaDown
        expr: up{job="kafka"} == 0
        for: 1m
        labels:
          severity: critical
          service: kafka
        annotations:
          summary: "Apache Kafka no responde"
          description: "El servicio de Kafka no está disponible"
          runbook_url: "https://docs.trading-bot.com/runbooks/kafka-down"

      - alert: RedisDown
        expr: up{job="redis"} == 0
        for: 1m
        labels:
          severity: critical
          service: redis
        annotations:
          summary: "Redis no responde"
          description: "El servicio de Redis no está disponible"
          runbook_url: "https://docs.trading-bot.com/runbooks/redis-down"

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.9
        for: 5m
        labels:
          severity: critical
          service: system
        annotations:
          summary: "Uso de memoria crítico"
          description: "El uso de memoria es del {{ $value | humanizePercentage }}"
          runbook_url: "https://docs.trading-bot.com/runbooks/high-memory-usage"

      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 95
        for: 10m
        labels:
          severity: critical
          service: system
        annotations:
          summary: "Uso de CPU crítico"
          description: "El uso de CPU es del {{ $value | humanizePercentage }}"
          runbook_url: "https://docs.trading-bot.com/runbooks/high-cpu-usage"

      - alert: DiskSpaceCritical
        expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) < 0.1
        for: 5m
        labels:
          severity: critical
          service: system
        annotations:
          summary: "Espacio en disco crítico"
          description: "Solo queda {{ $value | humanizePercentage }} de espacio en disco"
          runbook_url: "https://docs.trading-bot.com/runbooks/disk-space-critical"

  - name: trading_bot_warning
    rules:
      # Alertas de warning del sistema
      - alert: HighTickDropRate
        expr: rate(ticks_dropped_total[5m]) / rate(ticks_received_total[5m]) > 0.05
        for: 2m
        labels:
          severity: warning
          service: data-collection
        annotations:
          summary: "Alta tasa de ticks descartados"
          description: "La tasa de ticks descartados es del {{ $value | humanizePercentage }}"
          runbook_url: "https://docs.trading-bot.com/runbooks/high-tick-drop-rate"

      - alert: WebSocketDisconnected
        expr: websocket_connections_active == 0
        for: 30s
        labels:
          severity: warning
          service: data-collection
        annotations:
          summary: "Todas las conexiones WebSocket desconectadas"
          description: "No hay conexiones WebSocket activas"
          runbook_url: "https://docs.trading-bot.com/runbooks/websocket-disconnected"

      - alert: SlowModelInference
        expr: histogram_quantile(0.95, model_inference_time_seconds) > 1.0
        for: 5m
        labels:
          severity: warning
          service: ml-training
        annotations:
          summary: "Inferencia del modelo lenta"
          description: "El P95 del tiempo de inferencia es {{ $value }}s"
          runbook_url: "https://docs.trading-bot.com/runbooks/slow-model-inference"

      - alert: HighProcessingLatency
        expr: histogram_quantile(0.95, processing_latency_seconds) > 1.0
        for: 5m
        labels:
          severity: warning
          service: data-collection
        annotations:
          summary: "Alta latencia de procesamiento"
          description: "El P95 de la latencia de procesamiento es {{ $value }}s"
          runbook_url: "https://docs.trading-bot.com/runbooks/high-processing-latency"

      - alert: LowAccountBalance
        expr: account_balance_usd < 100
        for: 1m
        labels:
          severity: warning
          service: trading
        annotations:
          summary: "Balance de cuenta bajo"
          description: "El balance de cuenta es ${{ $value }}"
          runbook_url: "https://docs.trading-bot.com/runbooks/low-account-balance"

      - alert: HighErrorRate
        expr: rate(errors_total[5m]) > 10
        for: 2m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "Alta tasa de errores"
          description: "La tasa de errores es {{ $value }} errores/segundo"
          runbook_url: "https://docs.trading-bot.com/runbooks/high-error-rate"

      - alert: KafkaProducerErrors
        expr: kafka_producer_errors_total > 0
        for: 1m
        labels:
          severity: warning
          service: kafka
        annotations:
          summary: "Errores en Kafka producer"
          description: "Hay {{ $value }} errores en el producer de Kafka"
          runbook_url: "https://docs.trading-bot.com/runbooks/kafka-producer-errors"

      - alert: RedisConnectionIssues
        expr: redis_operations_failed_total > 0
        for: 1m
        labels:
          severity: warning
          service: redis
        annotations:
          summary: "Problemas de conexión con Redis"
          description: "Hay {{ $value }} operaciones fallidas en Redis"
          runbook_url: "https://docs.trading-bot.com/runbooks/redis-connection-issues"

  - name: trading_bot_info
    rules:
      # Alertas informativas
      - alert: TrainingCompleted
        expr: increase(training_epochs_completed_total[1h]) > 0
        for: 0s
        labels:
          severity: info
          service: ml-training
        annotations:
          summary: "Entrenamiento completado"
          description: "Entrenamiento completado para {{ $labels.symbol }}"
          runbook_url: "https://docs.trading-bot.com/runbooks/training-completed"

      - alert: LargeTradeExecuted
        expr: trade_amount_usd > 1000
        for: 0s
        labels:
          severity: info
          service: trading
        annotations:
          summary: "Trade grande ejecutado"
          description: "Trade de ${{ $value }} ejecutado en {{ $labels.symbol }}"
          runbook_url: "https://docs.trading-bot.com/runbooks/large-trade-executed"

      - alert: NewModelDeployed
        expr: increase(model_deployments_total[1h]) > 0
        for: 0s
        labels:
          severity: info
          service: ml-training
        annotations:
          summary: "Nuevo modelo desplegado"
          description: "Nuevo modelo {{ $labels.model_name }} desplegado"
          runbook_url: "https://docs.trading-bot.com/runbooks/new-model-deployed"

      - alert: SystemStartup
        expr: up{job="trading-bot-main"} == 1
        for: 0s
        labels:
          severity: info
          service: system
        annotations:
          summary: "Sistema iniciado"
          description: "El sistema Trading Bot ha sido iniciado"
          runbook_url: "https://docs.trading-bot.com/runbooks/system-startup"

  - name: trading_bot_performance
    rules:
      # Alertas de rendimiento
      - alert: LowThroughput
        expr: rate(ticks_processed_total[5m]) < 100
        for: 5m
        labels:
          severity: warning
          service: data-collection
        annotations:
          summary: "Throughput bajo"
          description: "El throughput es de {{ $value }} ticks/segundo"
          runbook_url: "https://docs.trading-bot.com/runbooks/low-throughput"

      - alert: HighMemoryUsageWarning
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.8
        for: 10m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "Uso de memoria alto"
          description: "El uso de memoria es del {{ $value | humanizePercentage }}"
          runbook_url: "https://docs.trading-bot.com/runbooks/high-memory-usage-warning"

      - alert: HighCPUUsageWarning
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 15m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "Uso de CPU alto"
          description: "El uso de CPU es del {{ $value | humanizePercentage }}"
          runbook_url: "https://docs.trading-bot.com/runbooks/high-cpu-usage-warning"

      - alert: DiskSpaceWarning
        expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) < 0.2
        for: 10m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "Espacio en disco bajo"
          description: "Solo queda {{ $value | humanizePercentage }} de espacio en disco"
          runbook_url: "https://docs.trading-bot.com/runbooks/disk-space-warning"
