# data_collection.yaml - Configuración de recolección de datos enterprise
# Ubicación: C:\TradingBot_v10\config\enterprise\data_collection.yaml

version: "1.0"

# Símbolos para recolección
symbols:
  primary: 
    - "BTCUSDT"
    - "ETHUSDT" 
    - "ADAUSDT"
    - "SOLUSDT"
    - "DOGEUSDT"
  secondary:
    - "AVAXUSDT"
    - "TONUSDT"
    - "BNBUSDT"
    - "XRPUSDT"
    - "LINKUSDT"
  
  # Configuración por símbolo
  config:
    BTCUSDT:
      priority: 1
      min_price_change: 0.01
      collection_frequency_ms: 100
    ETHUSDT:
      priority: 1  
      min_price_change: 0.01
      collection_frequency_ms: 100
    default:
      priority: 2
      min_price_change: 0.001
      collection_frequency_ms: 250

# Timeframes para colección
timeframes:
  real_time: ["tick"]
  aggregated: ["1m", "5m", "15m", "1h", "4h", "1d"]
  
  # Configuración por timeframe
  config:
    tick:
      buffer_size: 1000
      flush_interval_ms: 1000
    "1m":
      buffer_size: 100
      flush_interval_ms: 60000
    "5m":
      buffer_size: 50
      flush_interval_ms: 300000
    "1h":
      buffer_size: 24
      flush_interval_ms: 3600000

# WebSocket configuration
websocket:
  urls:
    bitget_spot: "wss://ws.bitget.com/spot/v1/stream"
    bitget_futures: "wss://ws.bitget.com/mix/v1/stream"
  
  connection:
    ping_interval: 20
    ping_timeout: 10
    close_timeout: 10
    max_message_size: 1048576  # 1MB
    
  reconnection:
    max_attempts: 10
    initial_delay: 1
    max_delay: 60
    backoff_factor: 2
    
  subscriptions:
    channels: ["ticker", "candle1m", "books1"]
    batch_size: 10  # Suscribirse de a 10 símbolos

# Data validation
validation:
  enabled: true
  
  # Validaciones de precio
  price:
    min_change_threshold: 0.0001  # 0.01%
    max_change_threshold: 0.2     # 20%
    outlier_detection: true
    outlier_threshold: 3.0        # 3 desviaciones estándar
    
  # Validaciones de volumen  
  volume:
    min_volume: 0.01
    max_volume_change: 10.0       # 1000%
    
  # Validaciones de timestamp
  timestamp:
    max_delay_seconds: 30
    duplicate_detection: true
    ordering_validation: true

# Data processing
processing:
  # Features técnicos en tiempo real
  features:
    price_based:
      - "sma_10"
      - "sma_20" 
      - "ema_12"
      - "ema_26"
      - "bollinger_upper"
      - "bollinger_lower"
    volume_based:
      - "volume_sma_10"
      - "volume_ema_10"
      - "vwap"
    momentum:
      - "rsi_14"
      - "macd"
      - "macd_signal"
      - "macd_histogram"
      
  # Configuración de cálculo
  calculation:
    batch_size: 100
    parallel_workers: 4
    cache_results: true
    cache_ttl_minutes: 10

# Storage configuration
storage:
  # Raw data storage
  raw_data:
    enabled: true
    format: "parquet"  # parquet, csv, json
    compression: "gzip"
    partition_by: ["symbol", "date"]
    path_template: "data/realtime/raw_ticks/{symbol}/{date}/ticks_{hour}.parquet"
    
  # Processed data storage
  processed_data:
    enabled: true
    format: "parquet"
    compression: "gzip" 
    partition_by: ["symbol", "timeframe", "date"]
    path_template: "data/realtime/processed_data/{symbol}/{timeframe}/{date}/data_{hour}.parquet"
    
  # Backup configuration
  backup:
    enabled: true
    frequency: "daily"  # hourly, daily, weekly
    retention_days: 30
    compression: true
    path_template: "backups/enterprise/data_collection/{date}/backup_{timestamp}.tar.gz"

# Performance monitoring
monitoring:
  metrics:
    enabled: true
    export_interval_seconds: 15
    
    # Métricas específicas de data collection
    data_collection:
      - "ticks_received_total"
      - "ticks_processed_total"
      - "ticks_dropped_total"
      - "processing_latency_seconds"
      - "websocket_connections_active"
      - "kafka_messages_sent_total"
      - "redis_operations_total"
      - "timescaledb_inserts_total"
      
  # Alertas
  alerts:
    enabled: true
    
    conditions:
      - name: "high_tick_drop_rate"
        condition: "ticks_dropped_total / ticks_received_total > 0.05"
        severity: "warning"
        message: "Alta tasa de ticks descartados: {value}%"
        
      - name: "websocket_disconnected"
        condition: "websocket_connections_active == 0"
        severity: "critical"
        message: "Todas las conexiones WebSocket desconectadas"
        
      - name: "high_processing_latency"
        condition: "processing_latency_seconds > 1.0"
        severity: "warning"
        message: "Alta latencia de procesamiento: {value}s"
        
      - name: "kafka_producer_errors"
        condition: "kafka_producer_errors_total > 0"
        severity: "error"
        message: "Errores en Kafka producer: {value}"

# Rate limiting
rate_limiting:
  enabled: true
  
  # Límites por servicio
  limits:
    bitget_api:
      requests_per_second: 10
      burst_size: 20
    kafka_producer:
      messages_per_second: 1000
      batch_size: 100
    redis_operations:
      operations_per_second: 1000
    timescaledb_inserts:
      inserts_per_second: 500
      batch_size: 1000

# Error handling
error_handling:
  retry:
    max_attempts: 3
    initial_delay: 1
    max_delay: 30
    backoff_factor: 2
    
  circuit_breaker:
    enabled: true
    failure_threshold: 5
    timeout_seconds: 60
    
  dead_letter_queue:
    enabled: true
    kafka_topic: "dead_letter_queue"
    max_retries: 3
