# experiments.yaml - Configuración de experimentos enterprise
# Ubicación: C:\TradingBot_v10\config\enterprise\experiments.yaml

version: "1.0"

# Configuración global de experimentos
experiments:
  # Configuración de MLflow
  mlflow:
    tracking_uri: "file:///C:/TradingBot_v10/mlflow"
    experiment_name_prefix: "TradingBot_Enterprise"
    
    # Configuración de runs
    run_config:
      run_name_template: "{model_architecture}_{symbols}_{timestamp}"
      tags:
        project: "trading_bot_v10"
        team: "ml_team"
        environment: "development"
        
    # Configuración de artifacts
    artifacts:
      model_artifacts: true
      training_plots: true
      confusion_matrix: true
      feature_importance: true
      hyperparameter_plots: true
      training_logs: true
      
  # Configuración de experimentos predefinidos
  predefined_experiments:
    # Experimento básico
    basic_training:
      name: "Basic Training"
      description: "Entrenamiento básico con LSTM-Attention"
      model_architecture: "lstm_attention"
      symbols: ["BTCUSDT", "ETHUSDT"]
      duration_hours: 2
      hyperparameter_tuning: false
      data_collection: true
      
    # Experimento de comparación de arquitecturas
    architecture_comparison:
      name: "Architecture Comparison"
      description: "Comparación de diferentes arquitecturas"
      model_architectures: ["lstm_attention", "transformer", "cnn_lstm"]
      symbols: ["BTCUSDT", "ETHUSDT", "ADAUSDT"]
      duration_hours: 4
      hyperparameter_tuning: true
      data_collection: true
      
    # Experimento de optimización intensiva
    intensive_optimization:
      name: "Intensive Hyperparameter Optimization"
      description: "Optimización intensiva de hiperparámetros"
      model_architecture: "lstm_attention"
      symbols: ["BTCUSDT", "ETHUSDT", "ADAUSDT", "SOLUSDT", "DOGEUSDT"]
      duration_hours: 8
      hyperparameter_tuning: true
      data_collection: true
      n_trials: 100
      
    # Experimento de ensemble
    ensemble_training:
      name: "Ensemble Training"
      description: "Entrenamiento de modelo ensemble"
      model_architecture: "ensemble"
      symbols: ["BTCUSDT", "ETHUSDT", "ADAUSDT", "SOLUSDT", "DOGEUSDT"]
      duration_hours: 6
      hyperparameter_tuning: true
      data_collection: true
      
    # Experimento de validación
    validation_experiment:
      name: "Model Validation"
      description: "Validación exhaustiva del mejor modelo"
      model_architecture: "lstm_attention"
      symbols: ["BTCUSDT", "ETHUSDT", "ADAUSDT", "SOLUSDT", "DOGEUSDT"]
      duration_hours: 3
      hyperparameter_tuning: false
      data_collection: true
      validation_only: true

# Configuración de métricas de experimentos
metrics:
  # Métricas principales
  primary_metrics:
    - name: "accuracy"
      weight: 1.0
      direction: "maximize"
      
    - name: "f1_score"
      weight: 0.8
      direction: "maximize"
      
    - name: "precision"
      weight: 0.7
      direction: "maximize"
      
    - name: "recall"
      weight: 0.7
      direction: "maximize"
      
  # Métricas secundarias
  secondary_metrics:
    - name: "auc_roc"
      weight: 0.6
      direction: "maximize"
      
    - name: "sharpe_ratio"
      weight: 0.5
      direction: "maximize"
      
    - name: "max_drawdown"
      weight: 0.4
      direction: "minimize"
      
    - name: "profit_factor"
      weight: 0.5
      direction: "maximize"
      
  # Métricas de sistema
  system_metrics:
    - name: "training_time_hours"
      weight: 0.2
      direction: "minimize"
      
    - name: "inference_time_ms"
      weight: 0.3
      direction: "minimize"
      
    - name: "model_size_mb"
      weight: 0.1
      direction: "minimize"

# Configuración de validación cruzada
cross_validation:
  enabled: true
  
  # Configuración de CV
  cv_config:
    n_splits: 5
    strategy: "time_series"  # time_series, stratified
    gap: 10  # Gap entre train y val para time series
    test_size: 0.2
    
  # Métricas a promediar en CV
  cv_metrics:
    - "accuracy"
    - "f1_score"
    - "precision"
    - "recall"
    - "auc_roc"
    
  # Configuración de scoring
  scoring:
    primary: "accuracy"
    secondary: "f1_score"

# Configuración de backtesting
backtesting:
  enabled: true
  
  # Configuración de backtesting
  backtest_config:
    initial_balance: 10000
    commission: 0.001
    slippage: 0.0001
    start_date: "2023-01-01"
    end_date: "2024-01-01"
    
  # Métricas de backtesting
  backtest_metrics:
    - "total_return"
    - "sharpe_ratio"
    - "max_drawdown"
    - "profit_factor"
    - "win_rate"
    - "average_trade_return"
    - "trades_per_day"
    
  # Configuración de estrategia
  strategy_config:
    position_sizing: "fixed"  # fixed, kelly, volatility
    risk_management: true
    stop_loss: 0.02  # 2%
    take_profit: 0.04  # 4%

# Configuración de comparación de modelos
model_comparison:
  enabled: true
  
  # Métodos de comparación
  comparison_methods:
    - "statistical_significance"
    - "cross_validation_comparison"
    - "backtesting_comparison"
    - "ensemble_performance"
    
  # Configuración de tests estadísticos
  statistical_tests:
    - name: "mcnemar_test"
      alpha: 0.05
      
    - name: "wilcoxon_test"
      alpha: 0.05
      
    - name: "t_test"
      alpha: 0.05

# Configuración de reporting
reporting:
  enabled: true
  
  # Tipos de reportes
  report_types:
    - "experiment_summary"
    - "model_comparison"
    - "hyperparameter_analysis"
    - "feature_importance"
    - "training_curves"
    - "confusion_matrix"
    - "roc_curves"
    - "backtesting_results"
    
  # Configuración de visualización
  visualization:
    save_plots: true
    plot_format: "png"
    plot_dpi: 300
    plot_style: "seaborn"
    color_palette: "husl"
    
  # Configuración de reportes
  report_config:
    output_dir: "reports/experiments"
    template: "enterprise_report"
    include_code: true
    include_data: false
    
  # Configuración de notificaciones
  notifications:
    enabled: true
    channels:
      - "email"
      - "slack"
      
    triggers:
      - "experiment_completed"
      - "best_model_found"
      - "experiment_failed"
      - "hyperparameter_optimization_completed"

# Configuración de experimentos A/B
ab_testing:
  enabled: true
  
  # Configuración de A/B tests
  ab_config:
    test_duration_days: 30
    traffic_split: 0.5  # 50/50 split
    significance_level: 0.05
    power: 0.8
    
  # Métricas para A/B testing
  ab_metrics:
    primary: "sharpe_ratio"
    secondary: ["accuracy", "f1_score", "max_drawdown"]
    
  # Configuración de variantes
  variants:
    control:
      name: "Current Model"
      model_path: "models/production/current"
      
    treatment:
      name: "New Model"
      model_path: "models/production/candidate"

# Configuración de experimentos de ensemble
ensemble_experiments:
  enabled: true
  
  # Configuración de ensemble
  ensemble_config:
    base_models:
      - "lstm_attention"
      - "transformer"
      - "cnn_lstm"
      
    ensemble_methods:
      - "weighted_average"
      - "voting"
      - "stacking"
      
    meta_learners:
      - "logistic_regression"
      - "random_forest"
      - "neural_network"
      
  # Configuración de validación de ensemble
  ensemble_validation:
    cross_validation: true
    backtesting: true
    statistical_tests: true

# Configuración de experimentos de transfer learning
transfer_learning:
  enabled: true
  
  # Configuración de transfer learning
  transfer_config:
    source_symbols: ["BTCUSDT", "ETHUSDT"]
    target_symbols: ["ADAUSDT", "SOLUSDT", "DOGEUSDT"]
    
    transfer_methods:
      - "fine_tuning"
      - "feature_extraction"
      - "adversarial_training"
      
  # Configuración de fine-tuning
  fine_tuning:
    learning_rate: 0.0001
    freeze_layers: 0.5  # Freeze 50% of layers
    epochs: 50

# Configuración de experimentos de data augmentation
data_augmentation_experiments:
  enabled: true
  
  # Configuración de data augmentation
  augmentation_config:
    techniques:
      - "gaussian_noise"
      - "time_warping"
      - "magnitude_warping"
      - "window_slicing"
      - "mixup"
      - "cutmix"
      
    augmentation_strengths:
      - "light"
      - "medium"
      - "heavy"
      
  # Configuración de validación
  augmentation_validation:
    cross_validation: true
    statistical_tests: true

# Configuración de experimentos de feature engineering
feature_engineering_experiments:
  enabled: true
  
  # Configuración de feature engineering
  feature_config:
    feature_groups:
      - "technical_indicators"
      - "price_features"
      - "volume_features"
      - "market_features"
      - "sentiment_features"
      
    feature_selection_methods:
      - "recursive_feature_elimination"
      - "mutual_info"
      - "lasso_selection"
      - "random_forest_importance"
      
  # Configuración de validación
  feature_validation:
    cross_validation: true
    feature_importance_analysis: true

# Configuración de experimentos de optimización
optimization_experiments:
  enabled: true
  
  # Configuración de optimización
  optimization_config:
    optimizers:
      - "adam"
      - "adamw"
      - "rmsprop"
      - "sgd"
      
    learning_rate_schedules:
      - "cosine_annealing"
      - "exponential_decay"
      - "step_decay"
      - "plateau"
      
    regularization_methods:
      - "dropout"
      - "batch_norm"
      - "layer_norm"
      - "weight_decay"
      - "label_smoothing"

# Configuración de experimentos de monitoreo
monitoring_experiments:
  enabled: true
  
  # Configuración de monitoreo
  monitoring_config:
    metrics:
      - "training_curves"
      - "validation_curves"
      - "gradient_norms"
      - "weight_distributions"
      - "activation_patterns"
      
    alerts:
      - "gradient_explosion"
      - "gradient_vanishing"
      - "overfitting"
      - "underfitting"
      - "data_drift"
      
  # Configuración de logging
  logging_config:
    log_frequency: "every_epoch"
    log_metrics: true
    log_gradients: false
    log_weights: false
    log_activations: false

# Configuración de experimentos de deployment
deployment_experiments:
  enabled: true
  
  # Configuración de deployment
  deployment_config:
    deployment_strategies:
      - "blue_green"
      - "canary"
      - "rolling"
      
    performance_metrics:
      - "latency"
      - "throughput"
      - "memory_usage"
      - "cpu_usage"
      
  # Configuración de A/B testing en producción
  production_ab_testing:
    enabled: true
    traffic_split: 0.1  # 10% para nuevo modelo
    duration_days: 7
    success_criteria:
      - "accuracy_improvement > 0.01"
      - "latency_increase < 0.1"
      - "error_rate_increase < 0.001"
