# security.yaml - Configuración de seguridad enterprise
# Ubicación: C:\TradingBot_v10\config\enterprise\security.yaml

version: "1.0"

# Configuración de encriptación
encryption:
  algorithm: "AES-256-GCM"
  key_derivation: "PBKDF2"
  iterations: 100000
  salt_length: 16
  
  # Datos a encriptar
  sensitive_fields:
    - "api_key"
    - "secret_key" 
    - "passphrase"
    - "password"
    - "database_password"
    - "redis_password"
    - "private_key"
    
  # Paths de claves
  key_storage:
    master_key_path: "security/keys/master.key"
    encryption_keys_path: "security/keys/encryption/"
    backup_keys_path: "backups/security/keys/"

# HashiCorp Vault (opcional para producción)
vault:
  enabled: false  # true para producción
  url: "http://localhost:8200"
  token_path: "security/vault/token"
  
  # Configuración de secrets
  secrets:
    api_credentials:
      path: "secret/trading-bot/api"
      fields: ["api_key", "secret_key", "passphrase"]
    database_credentials:
      path: "secret/trading-bot/database"
      fields: ["username", "password"]
    monitoring_credentials:
      path: "secret/trading-bot/monitoring"
      fields: ["grafana_password", "prometheus_password"]

# Audit logging
audit:
  enabled: true
  
  # Configuración de logs de auditoría
  logging:
    path: "logs/enterprise/security/audit.log"
    format: "json"
    rotation:
      max_size_mb: 50
      max_files: 100
      compression: true
      
  # Eventos a auditar
  events:
    authentication:
      - "login_attempt"
      - "login_success" 
      - "login_failure"
      - "logout"
    authorization:
      - "access_granted"
      - "access_denied"
      - "permission_change"
    data_access:
      - "data_read"
      - "data_write"
      - "data_delete"
      - "data_export"
    configuration:
      - "config_change"
      - "settings_update"
      - "user_preference_change"
    trading:
      - "order_placed"
      - "order_executed"
      - "order_cancelled"
      - "position_opened"
      - "position_closed"
    security:
      - "encryption_key_rotation"
      - "vault_access"
      - "security_alert"
      - "compliance_check"

# Compliance configuration
compliance:
  # GDPR
  gdpr:
    enabled: true
    data_retention_days: 2555  # 7 años
    anonymization_enabled: true
    right_to_be_forgotten: true
    
  # MiFID II
  mifid2:
    enabled: true
    transaction_reporting: true
    best_execution_reporting: true
    trade_reconstruction: true
    data_retention_years: 7
    
  # Reportes de compliance
  reporting:
    enabled: true
    frequency: "daily"
    path: "reports/compliance/{date}/compliance_report_{timestamp}.json"
    
    # Checks automáticos
    checks:
      - name: "data_retention_check"
        frequency: "daily"
        description: "Verificar retención de datos según normativas"
      - name: "encryption_check" 
        frequency: "daily"
        description: "Verificar encriptación de datos sensibles"
      - name: "access_control_check"
        frequency: "weekly"
        description: "Verificar controles de acceso"
      - name: "audit_log_check"
        frequency: "daily"
        description: "Verificar integridad de logs de auditoría"

# Access control
access_control:
  # Roles y permisos
  roles:
    admin:
      permissions:
        - "system_config"
        - "user_management"
        - "data_access"
        - "trading_control"
        - "monitoring_access"
        - "security_management"
    trader:
      permissions:
        - "trading_control"
        - "data_access"
        - "monitoring_access"
    analyst:
      permissions:
        - "data_access"
        - "monitoring_access"
    readonly:
      permissions:
        - "monitoring_access"
        
  # Configuración de sesiones
  sessions:
    timeout_minutes: 480  # 8 horas
    max_concurrent_sessions: 3
    session_encryption: true

# Network security
network:
  # TLS/SSL configuration
  tls:
    enabled: true
    min_version: "1.2"
    cipher_suites:
      - "ECDHE-RSA-AES256-GCM-SHA384"
      - "ECDHE-RSA-AES128-GCM-SHA256"
      - "ECDHE-RSA-AES256-SHA384"
      - "ECDHE-RSA-AES128-SHA256"
      
  # Firewall rules (informativo)
  firewall:
    allowed_ports:
      - 8000   # Prometheus metrics
      - 8050   # Dashboard
      - 9092   # Kafka
      - 6379   # Redis
      - 5432   # TimescaleDB
      - 9090   # Prometheus
      - 3000   # Grafana
      
    blocked_ports:
      - 22     # SSH (usar VPN)
      - 3389   # RDP (usar VPN)

# Anomaly detection
anomaly_detection:
  enabled: true
  
  # Detección de patrones anómalos
  patterns:
    unusual_trading_activity:
      enabled: true
      threshold_multiplier: 3.0
      lookback_hours: 24
      
    suspicious_data_access:
      enabled: true
      max_requests_per_minute: 100
      
    abnormal_system_usage:
      enabled: true
      cpu_threshold: 90
      memory_threshold: 85
      disk_threshold: 80
      
  # Respuesta a anomalías
  response:
    alert_enabled: true
    auto_block_enabled: false  # true para producción
    quarantine_enabled: true
    
# Secrets rotation
secrets_rotation:
  enabled: true
  
  # Frecuencia de rotación
  schedule:
    api_keys: "90d"      # 90 días
    database_passwords: "180d"  # 180 días
    encryption_keys: "365d"     # 1 año
    
  # Configuración de rotación
  rotation:
    advance_notice_days: 7
    grace_period_days: 3
    backup_old_secrets: true
