# Configuración del Bot de Telegram - Trading Bot v10 Enterprise
# =============================================================
# 
# Este archivo contiene la configuración del bot de Telegram para monitoreo
# y control del sistema de trading desde dispositivos móviles.
#
# IMPORTANTE: 
# - Reemplaza 937027893 con tu Chat ID real
# - El bot_token ya está configurado con el token proporcionado
# - Para obtener tu Chat ID, envía un mensaje al bot y revisa:
#   https://api.telegram.org/bot8422053215:AAH5hqD8472CCQyDTHfL8Zge9VXZNEJbdd8/getUpdates

telegram:
  # Token del bot (ya configurado)
  bot_token: "8422053215:AAH5hqD8472CCQyDTHfL8Zge9VXZNEJbdd8"
  
  # Chat ID del usuario autorizado (REEMPLAZAR)
  # Para obtener tu Chat ID:
  # 1. Envía un mensaje a @Trading_buurguees_Bot
  # 2. Visita: https://api.telegram.org/bot8422053215:AAH5hqD8472CCQyDTHfL8Zge9VXZNEJbdd8/getUpdates
  # 3. Busca "chat":{"id":123456789} y copia el número
  chat_id: "937027893"
  
  # Habilitar/deshabilitar el bot
  enabled: true
  
  # Intervalo de envío de métricas (en segundos)
  # 300 = 5 minutos, 600 = 10 minutos, 1800 = 30 minutos
  metrics_interval: 300
  
  # Configuración de alertas
  alert_thresholds:
    # Alerta si PnL del día supera este valor (en USD)
    pnl_alert: 1000
    
    # Alerta si drawdown supera este porcentaje
    risk_alert: 10
    
    # Alerta si latencia supera este valor (en ms)
    latency_alert: 100
    
    # Alerta si health score baja de este valor
    health_alert: 70

# Configuración del sistema integrado
system:
  # Dashboard
  dashboard:
    enabled: true
    host: "127.0.0.1"
    port: 8050
    auto_open: true
  
  # Control de comandos
  commands:
    require_confirmation: true
    confirmation_timeout: 300  # 5 minutos
    
  # Colas de comunicación
  queues:
    command_queue_size: 100
    status_queue_size: 100

# Configuración de seguridad
security:
  # Usar encriptación para el token (requiere ENCRYPTION_KEY en .env)
  encrypt_token: false
  
  # Cooldown entre alertas del mismo tipo (en segundos)
  alert_cooldown: 300
  
  # Máximo de mensajes por minuto
  rate_limit: 30

# Configuración de mensajes
messages:
  # Formato de mensajes (HTML o Markdown)
  parse_mode: "HTML"
  
  # Incluir timestamp en métricas
  include_timestamp: true
  
  # Límite de posiciones mostradas
  max_positions: 10
  
  # Incluir emojis en mensajes
  use_emojis: true

# Configuración de logging
logging:
  # Nivel de log para el bot de Telegram
  level: "INFO"
  
  # Archivo de log específico
  file: "logs/telegram_bot.log"
  
  # Incluir mensajes enviados en logs
  log_messages: true

# Configuración de desarrollo
development:
  # Modo debug (más logs, menos restricciones)
  debug_mode: false
  
  # Simular métricas si no hay datos reales
  simulate_metrics: false
  
  # Mostrar errores detallados en respuestas
  show_detailed_errors: false
