# Configuración para Scripts de Entrenamiento
# ===========================================

# Configuración general
general:
  log_level: INFO
  max_workers: 4
  timeout_seconds: 300

# Configuración de entrenamiento histórico
historical:
  cycle_size_bars: 500
  update_every_bars: 25
  max_cycles: 100
  data_directory: "data/historical"
  output_directory: "artifacts/historical"
  
  # Configuración de símbolos
  symbols:
    - "BTCUSDT"
    - "ETHUSDT"
    - "ADAUSDT"
    - "SOLUSDT"
    - "DOTUSDT"
  
  # Configuración de riesgo
  risk:
    initial_balance: 1000.0
    per_trade_pct: 0.5
    max_exposure_pct: 20.0
    stop_loss_pct: 2.0
    take_profit_pct: 4.0
  
  # Configuración de penalizaciones
  penalties:
    balance_reset_threshold: 0.0
    strategy_penalty:
      bad_score_delta: -0.15
      add_to_blacklist_after: 2
    max_resets_per_session: 5

# Configuración de entrenamiento en vivo
live:
  cycle_minutes: 30
  update_every_seconds: 5
  max_cycles: 1000
  data_directory: "data/live"
  output_directory: "artifacts/live"
  
  # Configuración de símbolos
  symbols:
    - "BTCUSDT"
    - "ETHUSDT"
    - "ADAUSDT"
    - "SOLUSDT"
    - "DOTUSDT"
  
  # Configuración de riesgo
  risk:
    initial_balance: 1000.0
    per_trade_pct: 0.5
    max_exposure_pct: 20.0
    stop_loss_pct: 2.0
    take_profit_pct: 4.0
  
  # Configuración de penalizaciones
  penalties:
    balance_reset_threshold: 0.0
    strategy_penalty:
      bad_score_delta: -0.15
      add_to_blacklist_after: 2
    max_resets_per_session: 5
  
  # Configuración de exchanges
  exchanges:
    binance:
      testnet: true
      websocket_url: "wss://testnet.binance.vision/ws/"
      api_url: "https://testnet.binance.vision/api/"
      rate_limit: 1200  # requests per minute
    bitget:
      testnet: true
      websocket_url: "wss://ws-sandbox.bitget.com/spot/v1/stream"
      api_url: "https://api-sandbox.bitget.com"
      rate_limit: 1000  # requests per minute

# Configuración de Telegram
telegram:
  update_rate_limit_sec: 3
  max_message_length: 4096
  enable_live_updates: true
  enable_cycle_summaries: true

# Configuración de logging
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/train.log"
  max_size_mb: 100
  backup_count: 5

# Configuración de persistencia
persistence:
  save_artifacts: true
  save_state: true
  save_trades: true
  save_metrics: true
  compression: true
  
  # Directorios
  artifacts_dir: "artifacts"
  state_dir: "state"
  trades_dir: "trades"
  metrics_dir: "telemetry"

# Configuración de métricas
metrics:
  calculate_sharpe: true
  calculate_sortino: true
  calculate_calmar: true
  calculate_max_drawdown: true
  calculate_win_rate: true
  calculate_profit_factor: true
  
  # Configuración de ventanas
  windows:
    short_term: 24  # horas
    medium_term: 168  # horas (1 semana)
    long_term: 720  # horas (1 mes)

# Configuración de estrategias
strategies:
  # Estrategias disponibles
  available:
    - "momentum"
    - "mean_reversion"
    - "breakout"
    - "scalping"
    - "swing"
  
  # Configuración por defecto
  default:
    type: "momentum"
    parameters:
      lookback_period: 20
      threshold: 0.02
      stop_loss: 0.02
      take_profit: 0.04
  
  # Configuración de selección
  selection:
    method: "random"  # random, weighted, best_performing
    weight_decay: 0.95
    min_performance: 0.1
    max_strategies: 10

# Configuración de validación
validation:
  enable_cross_validation: true
  cv_folds: 5
  test_size: 0.2
  validation_size: 0.2
  
  # Métricas de validación
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1_score"
    - "sharpe_ratio"
    - "max_drawdown"
    - "profit_factor"

# Configuración de optimización
optimization:
  enable_hyperparameter_tuning: true
  method: "optuna"  # optuna, grid_search, random_search
  n_trials: 100
  timeout_seconds: 3600
  
  # Parámetros a optimizar
  parameters:
    learning_rate:
      type: "float"
      low: 0.0001
      high: 0.01
      log: true
    batch_size:
      type: "categorical"
      choices: [16, 32, 64, 128]
    hidden_size:
      type: "int"
      low: 32
      high: 256
    num_layers:
      type: "int"
      low: 1
      high: 4

# Configuración de alertas
alerts:
  enable: true
  channels:
    - "telegram"
    - "log"
  
  # Umbrales de alerta
  thresholds:
    high_drawdown: 0.1  # 10%
    low_balance: 100.0  # $100
    high_latency: 1000  # 1 segundo
    low_win_rate: 0.3  # 30%
    high_loss_streak: 5  # trades consecutivos
  
  # Configuración de notificaciones
  notifications:
    frequency: "immediate"  # immediate, hourly, daily
    include_metrics: true
    include_charts: false
    max_length: 1000
