# training.yaml - Configuración de entrenamiento enterprise
# Ubicación: C:\TradingBot_v10\config\enterprise\training.yaml

version: "1.0"
environment: "development"  # development, staging, production

# Configuración global de entrenamiento
training:
  # Duración y scheduling
  duration:
    hours: 8
    max_epochs: 1000
    early_stopping_patience: 50
    min_epochs: 10
    
  # Configuración de datos
  data:
    symbols: ["BTCUSDT", "ETHUSDT", "ADAUSDT", "SOLUSDT", "DOGEUSDT"]
    timeframes: ["1h", "4h", "1d"]
    lookback_periods: 60
    prediction_horizon: 1
    train_split: 0.7
    val_split: 0.2
    test_split: 0.1
    batch_size: 64
    num_workers: 8
    pin_memory: true
    
  # Configuración de modelo
  model:
    architecture: "lstm_attention"  # lstm_attention, transformer, cnn_lstm
    input_features: 50
    hidden_size: 256
    num_layers: 3
    dropout: 0.2
    attention_heads: 8
    
  # Optimización
  optimization:
    optimizer: "adamw"
    learning_rate: 0.001
    weight_decay: 0.01
    lr_scheduler: "cosine_annealing"
    warmup_epochs: 10
    gradient_clip_val: 1.0
    
  # Regularización
  regularization:
    dropout: 0.2
    batch_norm: true
    layer_norm: true
    weight_decay: 0.01
    label_smoothing: 0.1

# Configuración de entrenamiento distribuido
distributed:
  enabled: true
  strategy: "ddp"  # ddp, ddp_spawn, deepspeed
  
  # Configuración de recursos
  resources:
    devices: "auto"  # auto, 1, 2, [0,1], etc.
    num_nodes: 1
    accelerator: "gpu"  # gpu, cpu, tpu
    precision: "16-mixed"  # 32, 16, bf16, 16-mixed
    
  # Configuración de DeepSpeed (opcional)
  deepspeed:
    enabled: false
    stage: 2  # 1, 2, 3
    offload_optimizer: false
    offload_parameters: false
    
  # Configuración de DDP
  ddp:
    find_unused_parameters: false
    gradient_as_bucket_view: true
    static_graph: true

# Configuración de checkpoints
checkpoints:
  enabled: true
  
  # Frecuencia de guardado
  save_frequency:
    every_n_epochs: 10
    every_n_steps: null
    monitor: "val_loss"
    mode: "min"
    save_top_k: 3
    
  # Paths de almacenamiento
  paths:
    base_dir: "models/trained_models/experiments"
    filename: "{epoch:02d}-{val_loss:.4f}-{val_accuracy:.4f}"
    
  # Configuración de resume
  resume:
    enabled: true
    auto_resume: true
    resume_from_checkpoint: null  # null para auto, o path específico
    
# Configuración de MLflow
mlflow:
  enabled: true
  
  # Configuración del servidor
  tracking_uri: "file:///C:/TradingBot_v10/mlflow"
  experiment_name: "TradingBot_Enterprise_Training"
  run_name_template: "{model_architecture}_{timestamp}_{symbols}"
  
  # Logging configuration
  logging:
    log_model: true
    log_params: true
    log_metrics: true
    log_artifacts: true
    log_every_n_epochs: 1
    log_every_n_steps: 100
    
  # Artifacts to log
  artifacts:
    - "config"
    - "model_architecture"
    - "training_plots"
    - "confusion_matrix"
    - "feature_importance"
    - "model_weights"
    
  # Tags automáticos
  tags:
    environment: "development"
    project: "trading_bot_v10"
    team: "ml_team"

# Configuración de callbacks
callbacks:
  # Early stopping
  early_stopping:
    enabled: true
    monitor: "val_loss"
    patience: 50
    mode: "min"
    min_delta: 0.001
    
  # Learning rate scheduling
  lr_scheduler:
    enabled: true
    monitor: "val_loss"
    mode: "min"
    factor: 0.5
    patience: 20
    cooldown: 10
    min_lr: 1e-7
    
  # Model checkpoint
  model_checkpoint:
    enabled: true
    monitor: "val_loss"
    mode: "min"
    save_top_k: 3
    save_last: true
    
  # Progress tracking
  progress_bar:
    enabled: true
    refresh_rate: 10
    
  # Prometheus metrics
  prometheus_metrics:
    enabled: true
    port: 8002
    metrics_prefix: "training"
    
  # Custom callbacks
  custom:
    - name: "GradientNormCallback"
      enabled: true
      log_every_n_steps: 100
      
    - name: "ModelComplexityCallback"
      enabled: true
      
    - name: "DataQualityCallback"
      enabled: true
      check_every_n_epochs: 10

# Configuración de validación
validation:
  enabled: true
  
  # Frecuencia de validación
  frequency:
    check_val_every_n_epoch: 1
    val_check_interval: 1.0  # Fraction of training epoch
    
  # Métricas de validación
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1_score"
    - "auc_roc"
    - "confusion_matrix"
    - "classification_report"
    
  # Cross-validation
  cross_validation:
    enabled: false
    k_folds: 5
    strategy: "time_series"  # time_series, stratified

# Configuración de testing
testing:
  enabled: true
  
  # Métricas de test
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1_score"
    - "auc_roc"
    - "sharpe_ratio"
    - "max_drawdown"
    - "profit_factor"
    
  # Backtesting
  backtesting:
    enabled: true
    initial_balance: 10000
    commission: 0.001
    slippage: 0.0001

# Configuración de features
features:
  # Features técnicos
  technical:
    price_features:
      - "sma_10"
      - "sma_20"
      - "sma_50"
      - "ema_12"
      - "ema_26"
      - "ema_50"
      - "bollinger_upper"
      - "bollinger_lower"
      - "bollinger_middle"
      - "rsi_14"
      - "rsi_7"
      - "macd"
      - "macd_signal"
      - "macd_histogram"
      - "stoch_k"
      - "stoch_d"
      - "williams_r"
      - "atr_14"
      - "adx_14"
      - "cci_20"
      
    volume_features:
      - "volume_sma_10"
      - "volume_ema_10"
      - "vwap"
      - "volume_profile"
      - "obv"
      - "ad_line"
      - "cmf"
      
    momentum_features:
      - "roc_10"
      - "momentum_10"
      - "trix"
      - "ultimate_oscillator"
      
  # Features de precio
  price_features:
    - "returns_1"
    - "returns_5"
    - "returns_10"
    - "log_returns"
    - "volatility_10"
    - "volatility_30"
    - "price_change_pct"
    - "high_low_ratio"
    - "open_close_ratio"
    
  # Features de mercado
  market_features:
    - "market_cap_rank"
    - "dominance_btc"
    - "fear_greed_index"
    - "funding_rate"
    - "open_interest"
    
  # Feature engineering
  engineering:
    polynomial_features: false
    interaction_features: true
    lag_features: [1, 2, 3, 5, 10]
    rolling_statistics: [5, 10, 20, 50]
    
# Configuración de data augmentation
data_augmentation:
  enabled: true
  
  techniques:
    - name: "gaussian_noise"
      probability: 0.3
      std: 0.01
      
    - name: "time_warping"
      probability: 0.2
      sigma: 0.2
      
    - name: "magnitude_warping"
      probability: 0.2
      sigma: 0.2
      
    - name: "window_slicing"
      probability: 0.3
      reduce_ratio: 0.9

# Configuración de monitoreo
monitoring:
  enabled: true
  
  # Métricas a monitorear
  metrics:
    training:
      - "train_loss"
      - "train_accuracy"
      - "learning_rate"
      - "epoch_time"
      - "gpu_memory_usage"
      - "cpu_usage"
      
    validation:
      - "val_loss"
      - "val_accuracy"
      - "val_precision"
      - "val_recall"
      - "val_f1"
      
    system:
      - "memory_usage"
      - "gpu_utilization"
      - "disk_usage"
      - "network_io"
      
  # Alertas
  alerts:
    enabled: true
    
    conditions:
      - name: "training_loss_plateau"
        condition: "no_improvement_for_epochs > 20"
        action: "reduce_lr"
        
      - name: "high_gpu_memory"
        condition: "gpu_memory_usage > 0.9"
        action: "alert"
        
      - name: "training_divergence"
        condition: "train_loss > val_loss * 2"
        action: "early_stop"

# Configuración de logging
logging:
  level: "INFO"
  
  # Configuración de archivos
  files:
    main:
      path: "logs/enterprise/training/main.log"
      max_size_mb: 100
      backup_count: 10
      
    experiments:
      path: "logs/enterprise/training/experiments/{experiment_id}.log"
      max_size_mb: 50
      backup_count: 5
      
    performance:
      path: "logs/enterprise/training/performance/performance.log"
      max_size_mb: 25
      backup_count: 20
      
  # Formatters
  formatters:
    detailed: "%(asctime)s - %(name)s - %(levelname)s - %(funcName)s:%(lineno)d - %(message)s"
    simple: "%(asctime)s - %(levelname)s - %(message)s"

# Configuración de recursos
resources:
  # Límites de memoria
  memory:
    max_ram_gb: 16
    max_vram_gb: 8
    
  # Límites de CPU
  cpu:
    max_cores: 8
    max_usage_percent: 90
    
  # Límites de almacenamiento
  storage:
    max_disk_gb: 100
    checkpoint_retention_days: 30
    log_retention_days: 90
    
  # Configuración de workers
  workers:
    dataloader_workers: 8
    preprocessing_workers: 4
    
# Configuración de debugging
debugging:
  enabled: false
  
  # Configuración de profiling
  profiling:
    enabled: false
    profile_memory: true
    profile_cpu: true
    output_dir: "logs/enterprise/training/profiling"
    
  # Configuración de debugging
  debug:
    detect_anomaly: false
    log_gradients: false
    log_weights: false
    save_intermediate_outputs: false
