# Ruta: config/agents_config.yaml
# agents_config.yaml - Configuración de agentes por símbolo
# Ubicación: config/agents_config.yaml

version: "1.0"

# Configuración general de agentes
agents:
  enabled: true
  max_concurrent_agents: 10
  agent_timeout: 300  # seconds
  restart_on_failure: true
  max_restart_attempts: 3
  restart_delay: 30  # seconds

# Configuración por símbolo
symbols:
  BTCUSDT:
    enabled: true
    priority: 1
    model_path: "agents/BTCUSDT/models/model.pkl"
    strategies_path: "agents/BTCUSDT/strategies/strategies.json"
    state_path: "agents/BTCUSDT/state/agent_state.json"
    logs_path: "agents/BTCUSDT/logs/"
    
    # Configuración de trading
    trading:
      max_position_size: 0.1  # 10% del capital
      min_confidence: 0.6
      stop_loss_pct: 0.02
      take_profit_pct: 0.04
      max_leverage: 125
      
    # Configuración de ML
    ml:
      model_type: "lstm_attention"
      retrain_frequency: "daily"
      backtest_period: 30
      feature_importance: true
      
    # Configuración de monitoreo
    monitoring:
      performance_tracking: true
      resource_monitoring: true
      alert_on_errors: true
      alert_on_high_memory: true
      memory_threshold: 80  # percentage
      
  ETHUSDT:
    enabled: true
    priority: 2
    model_path: "agents/ETHUSDT/models/model.pkl"
    strategies_path: "agents/ETHUSDT/strategies/strategies.json"
    state_path: "agents/ETHUSDT/state/agent_state.json"
    logs_path: "agents/ETHUSDT/logs/"
    
    trading:
      max_position_size: 0.08
      min_confidence: 0.65
      stop_loss_pct: 0.025
      take_profit_pct: 0.05
      max_leverage: 100
      
    ml:
      model_type: "lstm_attention"
      retrain_frequency: "daily"
      backtest_period: 30
      feature_importance: true
      
    monitoring:
      performance_tracking: true
      resource_monitoring: true
      alert_on_errors: true
      alert_on_high_memory: true
      memory_threshold: 80
      
  ADAUSDT:
    enabled: true
    priority: 3
    model_path: "agents/ADAUSDT/models/model.pkl"
    strategies_path: "agents/ADAUSDT/strategies/strategies.json"
    state_path: "agents/ADAUSDT/state/agent_state.json"
    logs_path: "agents/ADAUSDT/logs/"
    
    trading:
      max_position_size: 0.05
      min_confidence: 0.7
      stop_loss_pct: 0.03
      take_profit_pct: 0.06
      max_leverage: 50
      
    ml:
      model_type: "lstm_attention"
      retrain_frequency: "weekly"
      backtest_period: 30
      feature_importance: true
      
    monitoring:
      performance_tracking: true
      resource_monitoring: true
      alert_on_errors: true
      alert_on_high_memory: true
      memory_threshold: 80
      
  SOLUSDT:
    enabled: true
    priority: 4
    model_path: "agents/SOLUSDT/models/model.pkl"
    strategies_path: "agents/SOLUSDT/strategies/strategies.json"
    state_path: "agents/SOLUSDT/state/agent_state.json"
    logs_path: "agents/SOLUSDT/logs/"
    
    trading:
      max_position_size: 0.05
      min_confidence: 0.7
      stop_loss_pct: 0.03
      take_profit_pct: 0.06
      max_leverage: 50
      
    ml:
      model_type: "lstm_attention"
      retrain_frequency: "weekly"
      backtest_period: 30
      feature_importance: true
      
    monitoring:
      performance_tracking: true
      resource_monitoring: true
      alert_on_errors: true
      alert_on_high_memory: true
      memory_threshold: 80
      
  DOGEUSDT:
    enabled: true
    priority: 5
    model_path: "agents/DOGEUSDT/models/model.pkl"
    strategies_path: "agents/DOGEUSDT/strategies/strategies.json"
    state_path: "agents/DOGEUSDT/state/agent_state.json"
    logs_path: "agents/DOGEUSDT/logs/"
    
    trading:
      max_position_size: 0.03
      min_confidence: 0.75
      stop_loss_pct: 0.035
      take_profit_pct: 0.07
      max_leverage: 25
      
    ml:
      model_type: "lstm_attention"
      retrain_frequency: "weekly"
      backtest_period: 30
      feature_importance: true
      
    monitoring:
      performance_tracking: true
      resource_monitoring: true
      alert_on_errors: true
      alert_on_high_memory: true
      memory_threshold: 80

# Configuración de modelos ML
ml_models:
  default_architecture: "lstm_attention"
  learning_rate: 0.001
  batch_size: 32
  epochs: 100
  hidden_size: 128
  num_layers: 2
  dropout: 0.2
  
  # Configuración de entrenamiento
  training:
    validation_split: 0.2
    early_stopping: true
    patience: 10
    min_delta: 0.001
    restore_best_weights: true
    
  # Configuración de features
  features:
    technical_indicators: true
    price_features: true
    volume_features: true
    time_features: true
    lag_features: 20
    
  # Configuración de evaluación
  evaluation:
    metrics: ["accuracy", "precision", "recall", "f1_score", "sharpe_ratio"]
    cross_validation: true
    cv_folds: 5

# Configuración de estrategias
strategies:
  default_strategy: "ml_strategy"
  
  # Estrategias disponibles
  available_strategies:
    - name: "ml_strategy"
      enabled: true
      weight: 0.6
      
    - name: "momentum_strategy"
      enabled: true
      weight: 0.2
      
    - name: "mean_reversion_strategy"
      enabled: true
      weight: 0.2
      
  # Configuración de ejecución
  execution:
    parallel_execution: true
    max_concurrent_strategies: 3
    strategy_timeout: 30  # seconds
    
  # Configuración de señales
  signals:
    min_confidence: 0.6
    max_signals_per_minute: 10
    signal_cooldown: 60  # seconds

# Configuración de logging por agente
logging:
  agent_logs_enabled: true
  log_level: "INFO"
  
  # Configuración de logs
  log_config:
    - name: "agent_{symbol}.log"
      level: "INFO"
      max_size: "5MB"
      backup_count: 3
      
    - name: "trading_{symbol}.log"
      level: "INFO"
      max_size: "10MB"
      backup_count: 5
      
    - name: "ml_{symbol}.log"
      level: "INFO"
      max_size: "8MB"
      backup_count: 3
      
    - name: "errors_{symbol}.log"
      level: "ERROR"
      max_size: "2MB"
      backup_count: 2

# Configuración de monitoreo
monitoring:
  performance_tracking: true
  resource_monitoring: true
  
  # Métricas de performance
  performance_metrics:
    - "total_trades"
    - "win_rate"
    - "sharpe_ratio"
    - "max_drawdown"
    - "total_pnl"
    - "avg_trade_duration"
    
  # Métricas de recursos
  resource_metrics:
    - "memory_usage"
    - "cpu_usage"
    - "disk_usage"
    - "network_io"
    
  # Alertas
  alerts:
    alert_on_errors: true
    alert_on_high_memory: true
    alert_on_low_performance: true
    memory_threshold: 80  # percentage
    performance_threshold: 0.5  # sharpe ratio