# Ruta: config/control_config.yaml
# control_config.yaml - Configuración de control del bot
# Ubicación: config/control_config.yaml

version: "1.0"

# Configuración de Telegram
telegram:
  bot_token: "8422053215:AAH5hqD8472CCQyDTHfL8Zge9VXZNEJbdd8"  # Configurar en .env
  chat_id: "937027893"    # Configurar en .env
  rate_limit: 10  # messages per minute
  use_emojis: true
  parse_mode: "Markdown"
  timeout: 30  # seconds
  
  # Comandos disponibles
  commands:
    - "/start"
    - "/status"
    - "/metrics"
    - "/trades"
    - "/positions"
    - "/risk"
    - "/config"
    - "/logs"
    - "/stop"
    - "/restart"
    - "/help"

# Configuración de comandos
commands:
  require_confirmation: true
  confirmation_timeout: 30  # seconds
  max_concurrent_commands: 3
  command_history_size: 100
  
  # Comandos críticos que requieren confirmación
  critical_commands:
    - "/stop"
    - "/restart"
    - "/config"
    - "/risk"
    
  # Comandos que requieren autenticación
  authenticated_commands:
    - "/config"
    - "/logs"
    - "/stop"
    - "/restart"

# Configuración de seguridad
security:
  authorized_chat_ids: []  # Lista de chat IDs autorizados
  rate_limiting:
    enabled: true
    max_requests_per_minute: 20
    max_requests_per_hour: 100
    block_duration: 300  # seconds
    
  # Auditoría de comandos
  audit_logging:
    log_all_commands: true
    retention_days: 30
    log_file: "logs/audit.log"
    
  # Timeout de comandos
  command_timeout: 60  # seconds
  max_command_duration: 300  # seconds

# Configuración de métricas
metrics:
  collection_interval: 30  # seconds
  prometheus_port: 8003
  export_interval: 60  # seconds
  
  # Métricas específicas
  trading_metrics:
    - "trades_total"
    - "pnl_gauge"
    - "win_rate"
    - "sharpe_ratio"
    - "max_drawdown"
    
  system_metrics:
    - "memory_usage"
    - "cpu_usage"
    - "disk_usage"
    - "network_io"
    
  api_metrics:
    - "api_calls_total"
    - "api_errors_total"
    - "api_latency"

# Configuración de alertas
alerts:
  enabled: true
  
  # Condiciones de alerta
  conditions:
    large_loss:
      threshold: -1000  # USD
      enabled: true
      
    daily_limit_reached:
      threshold: 0.05  # 5%
      enabled: true
      
    high_memory_usage:
      threshold: 80  # percentage
      enabled: true
      
    api_errors:
      threshold: 10  # errors per minute
      enabled: true
      
    connection_lost:
      timeout: 60  # seconds
      enabled: true
  
  # Canales de alerta
  channels:
    telegram:
      enabled: true
      priority: "high"
      
    email:
      enabled: false
      priority: "medium"
      
    webhook:
      enabled: false
      url: ""
      priority: "low"

# Configuración del sistema
system:
  max_workers: 4
  memory_limit: "2GB"
  cpu_limit: 80  # percentage
  health_check_interval: 30  # seconds
  
  # Configuración de logging
  logging:
    level: "INFO"
    file: "logs/control.log"
    console_output: true
    max_size: "10MB"
    backup_count: 5
    
  # Configuración de red
  network:
    timeout: 30  # seconds
    retry_attempts: 3
    retry_delay: 1  # seconds
    max_connections: 10