# Configuración de Control del Bot Trading v10 Enterprise
# ======================================================

# Configuración de Telegram
telegram:
  enabled: true
  bot_token: "${TELEGRAM_BOT_TOKEN}"
  chat_id: "${TELEGRAM_CHAT_ID}"
  rate_limit: 30
  timeout: 10
  retry_attempts: 3
  parse_mode: "HTML"
  use_emojis: true

# Configuración de comandos
commands:
  require_confirmation: true
  confirmation_timeout: 300
  max_concurrent_commands: 5
  command_timeout: 60

# Configuración de seguridad
security:
  authorized_chat_ids:
    - "937027893"  # Chat ID principal
  rate_limiting:
    enabled: true
    max_requests_per_minute: 30
    burst_limit: 10
  audit_logging:
    enabled: true
    log_all_commands: true
    retention_days: 30

# Configuración de logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/bot.log"
  max_file_size: "10MB"
  backup_count: 5
  console_output: true
  encoding: "utf-8"

# Configuración de métricas
metrics:
  enabled: true
  collection_interval: 60
  prometheus_port: 8003
  export_interval: 30

# Configuración de alertas
alerts:
  enabled: true
  channels:
    - "telegram"
    - "console"
  events:
    - "command_executed"
    - "error_occurred"
    - "trading_started"
    - "trading_stopped"
    - "large_loss"
    - "daily_limit_reached"

# Configuración de sistema
system:
  max_workers: 4
  memory_limit: "2GB"
  cpu_limit: 80
  health_check_interval: 30
  auto_restart_on_error: true
  graceful_shutdown_timeout: 30
