# Configuración de Datos - Bot Trading v10 Enterprise
# ==================================================

# Configuración de base de datos
database:
  primary: "sqlite"
  sqlite:
    path: "data/trading_bot.db"
    per_symbol: true
    compression: true
    vacuum_frequency: "weekly"
  
  redis:
    enabled: true
    url: "redis://localhost:6379"
    db: 0
    max_connections: 10
    timeout: 5
  
  timescaledb:
    enabled: false
    url: "postgresql://user:password@localhost:5432/trading_bot"
    max_connections: 20

# Configuración de datos históricos
historical_data:
  enabled: true
  years: 1
  timeframes: ["1m", "5m", "15m", "1h", "4h", "1d"]
  symbols: ["BTCUSDT", "ETHUSDT", "ADAUSDT", "SOLUSDT", "DOGEUSDT", "AVAXUSDT", "TONUSDT", "XRPUSDT", "LINKUSDT"]
  
  storage:
    format: "sqlite"
    structure: "symbol_based"
    database_per_symbol: true
    compression_enabled: true
    compression_days: 180
  
  verification:
    auto_verify_coverage: true
    min_coverage_days: 365
    download_missing: true
    verification_interval_hours: 24

# Configuración de datos en tiempo real
real_time_data:
  enabled: true
  symbols: ["BTCUSDT", "ETHUSDT", "ADAUSDT", "SOLUSDT", "DOGEUSDT", "AVAXUSDT", "TONUSDT", "XRPUSDT", "LINKUSDT"]
  timeframes: ["1m", "5m", "15m", "1h", "4h", "1d"]
  data_types: ["kline", "ticker", "orderbook"]
  
  collection:
    interval: 1  # segundos
    batch_size: 100
    buffer_size: 1000
    flush_interval: 10  # segundos

# Configuración de alineación temporal
alignment:
  enabled: true
  base_timeframe: "5m"
  tolerance_minutes: 1
  min_data_coverage: 0.95
  max_gap_minutes: 60
  auto_align_on_startup: true
  
  # Configuración por timeframe
  timeframe_config:
    "1m":
      priority: 1
      buffer_size: 1000
      flush_interval_ms: 60000
      required_for_trading: true
    "5m":
      priority: 1
      buffer_size: 200
      flush_interval_ms: 300000
      required_for_trading: true
      base_for_alignment: true
    "15m":
      priority: 2
      buffer_size: 100
      flush_interval_ms: 900000
      required_for_trading: true
    "1h":
      priority: 2
      buffer_size: 24
      flush_interval_ms: 3600000
      required_for_ml: true
    "4h":
      priority: 3
      buffer_size: 6
      flush_interval_ms: 14400000
      required_for_ml: true
    "1d":
      priority: 3
      buffer_size: 1
      flush_interval_ms: 86400000
      required_for_ml: true

# Configuración de limpieza de datos
data_cleanup:
  enabled: true
  remove_duplicates: true
  fill_gaps: true
  max_gap_minutes: 60
  outlier_threshold: 3.0
  min_volume_threshold: 0.0

# Configuración de backup
backup:
  enabled: true
  frequency: "daily"
  retention_days: 30
  compression: true
  include_logs: true
  include_models: true
  include_strategies: true

# Configuración de migración
migration:
  enabled: true
  auto_migrate: true
  backup_legacy: true
  validate_after_migration: true
