# Ruta: config/logging_config.yaml
# logging_config.yaml - Configuración detallada de logging
# Ubicación: config/logging_config.yaml

version: "1.0"

# Configuración general de logging
logging:
  version: 1
  disable_existing_loggers: false
  
  # Formatters
  formatters:
    standard:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
      
    detailed:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(filename)s:%(lineno)d - %(funcName)s - %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
      
    json:
      format: '{"timestamp": "%(asctime)s", "logger": "%(name)s", "level": "%(levelname)s", "message": "%(message)s", "module": "%(filename)s", "function": "%(funcName)s", "line": %(lineno)d}'
      datefmt: "%Y-%m-%d %H:%M:%S"
      
    audit:
      format: "%(asctime)s - AUDIT - %(levelname)s - %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
      
    trading:
      format: "%(asctime)s - TRADING - %(levelname)s - %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
      
    ml:
      format: "%(asctime)s - ML - %(levelname)s - %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"

  # Handlers
  handlers:
    console:
      class: "logging.StreamHandler"
      level: "INFO"
      formatter: "standard"
      stream: "ext://sys.stdout"
      
    file:
      class: "logging.handlers.RotatingFileHandler"
      level: "INFO"
      formatter: "detailed"
      filename: "logs/bot.log"
      maxBytes: 10485760  # 10MB
      backupCount: 5
      encoding: "utf-8"
      
    error_handler:
      class: "logging.handlers.RotatingFileHandler"
      level: "ERROR"
      formatter: "detailed"
      filename: "logs/errors.log"
      maxBytes: 5242880  # 5MB
      backupCount: 3
      encoding: "utf-8"
      
    audit_handler:
      class: "logging.handlers.RotatingFileHandler"
      level: "INFO"
      formatter: "audit"
      filename: "logs/audit.log"
      maxBytes: 10485760  # 10MB
      backupCount: 10
      encoding: "utf-8"
      
    trading_handler:
      class: "logging.handlers.RotatingFileHandler"
      level: "INFO"
      formatter: "trading"
      filename: "logs/trading.log"
      maxBytes: 52428800  # 50MB
      backupCount: 7
      encoding: "utf-8"
      
    ml_handler:
      class: "logging.handlers.RotatingFileHandler"
      level: "INFO"
      formatter: "ml"
      filename: "logs/ml.log"
      maxBytes: 31457280  # 30MB
      backupCount: 5
      encoding: "utf-8"
      
    data_handler:
      class: "logging.handlers.RotatingFileHandler"
      level: "INFO"
      formatter: "detailed"
      filename: "logs/data.log"
      maxBytes: 20971520  # 20MB
      backupCount: 5
      encoding: "utf-8"
      
    monitoring_handler:
      class: "logging.handlers.RotatingFileHandler"
      level: "INFO"
      formatter: "detailed"
      filename: "logs/monitoring.log"
      maxBytes: 15728640  # 15MB
      backupCount: 5
      encoding: "utf-8"
      
    security_handler:
      class: "logging.handlers.RotatingFileHandler"
      level: "WARNING"
      formatter: "detailed"
      filename: "logs/security.log"
      maxBytes: 10485760  # 10MB
      backupCount: 10
      encoding: "utf-8"

  # Loggers
  loggers:
    __main__:
      level: "INFO"
      handlers: ["console", "file"]
      propagate: false
      
    control:
      level: "INFO"
      handlers: ["console", "file", "audit_handler"]
      propagate: false
      
    core.trading:
      level: "INFO"
      handlers: ["trading_handler", "console"]
      propagate: false
      
    core.ml:
      level: "INFO"
      handlers: ["ml_handler", "console"]
      propagate: false
      
    core.data:
      level: "INFO"
      handlers: ["data_handler", "console"]
      propagate: false
      
    core.monitoring:
      level: "INFO"
      handlers: ["monitoring_handler", "console"]
      propagate: false
      
    core.security:
      level: "WARNING"
      handlers: ["console", "security_handler", "audit_handler"]
      propagate: false
      
    core.agents:
      level: "INFO"
      handlers: ["file", "console"]
      propagate: false
      
    scripts:
      level: "INFO"
      handlers: ["file", "console"]
      propagate: false
      
    # Loggers específicos para agentes
    agents.BTCUSDT:
      level: "INFO"
      handlers: ["file", "console"]
      propagate: false
      
    agents.ETHUSDT:
      level: "INFO"
      handlers: ["file", "console"]
      propagate: false
      
    agents.ADAUSDT:
      level: "INFO"
      handlers: ["file", "console"]
      propagate: false
      
    agents.SOLUSDT:
      level: "INFO"
      handlers: ["file", "console"]
      propagate: false
      
    agents.DOGEUSDT:
      level: "INFO"
      handlers: ["file", "console"]
      propagate: false

  # Root logger
  root:
    level: "INFO"
    handlers: ["console", "file", "error_handler"]

# Filtros
filters:
  sensitive_data:
    class: "core.logging.filters.SensitiveDataFilter"
    patterns:
      - "password"
      - "api_key"
      - "secret"
      - "token"
      - "private_key"
      - "passphrase"
      - "bot_token"
      - "chat_id"
    replacement: "[REDACTED]"
    
  trading_data:
    class: "core.logging.filters.TradingDataFilter"
    patterns:
      - "pnl"
      - "balance"
      - "position"
      - "leverage"
    log_level: "DEBUG"

# Configuración de rotación
rotation:
  strategy: "size_and_time"
  max_size: "50MB"
  max_time: "1 day"
  backup_count: 7
  compress: true
  compress_format: "gz"

# Configuración de limpieza
cleanup:
  enabled: true
  max_age_days: 30
  max_total_size: "1GB"
  schedule: "daily"
  time: "02:00"