# Ruta: config/logs_config.yaml
# logs_config.yaml - Configuración de logging por módulo y agente
# Ubicación: config/logs_config.yaml

version: "1.0"

# Configuración general de logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"
  console_output: true
  file_output: true

# Configuración por módulo
modules:
  bot:
    level: "INFO"
    file: "logs/bot.log"
    max_size: "10MB"
    backup_count: 5
    console: true
    
  trading:
    level: "INFO"
    file: "logs/trading.log"
    max_size: "50MB"
    backup_count: 7
    console: false
    
  ml:
    level: "INFO"
    file: "logs/ml.log"
    max_size: "30MB"
    backup_count: 5
    console: false
    
  data:
    level: "INFO"
    file: "logs/data.log"
    max_size: "20MB"
    backup_count: 5
    console: false
    
  agents:
    level: "INFO"
    file: "logs/agents.log"
    max_size: "25MB"
    backup_count: 5
    console: false
    
  monitoring:
    level: "INFO"
    file: "logs/monitoring.log"
    max_size: "15MB"
    backup_count: 5
    console: false
    
  security:
    level: "WARNING"
    file: "logs/security.log"
    max_size: "10MB"
    backup_count: 10
    console: true
    
  errors:
    level: "ERROR"
    file: "logs/errors.log"
    max_size: "5MB"
    backup_count: 3
    console: true

# Configuración de logs por agente
agent_logs:
  enabled: true
  base_path: "agents/{symbol}/logs"
  log_level: "INFO"
  
  # Logs específicos por agente
  agent_logs:
    - name: "agent_{symbol}.log"
      level: "INFO"
      max_size: "5MB"
      backup_count: 3
      
    - name: "trading_{symbol}.log"
      level: "INFO"
      max_size: "10MB"
      backup_count: 5
      
    - name: "ml_{symbol}.log"
      level: "INFO"
      max_size: "8MB"
      backup_count: 3
      
    - name: "errors_{symbol}.log"
      level: "ERROR"
      max_size: "2MB"
      backup_count: 2

# Filtros para datos sensibles
filters:
  sensitive_data:
    enabled: true
    patterns:
      - "password"
      - "api_key"
      - "secret"
      - "token"
      - "private_key"
      - "passphrase"
      - "bot_token"
      - "chat_id"
    replacement: "[REDACTED]"
    
  trading_data:
    enabled: true
    patterns:
      - "pnl"
      - "balance"
      - "position"
      - "leverage"
    log_level: "DEBUG"

# Rotación de logs
rotation:
  strategy: "size_and_time"
  max_size: "50MB"
  max_time: "1 day"
  backup_count: 7
  compress: true
  compress_format: "gz"

# Limpieza de logs
cleanup:
  enabled: true
  max_age_days: 30
  max_total_size: "1GB"
  schedule: "daily"
  time: "02:00"