# Configuración de Monitoreo - Bot Trading v10 Enterprise
# =======================================================

# Configuración general de monitoreo
monitoring:
  enabled: true
  update_interval: 60  # segundos
  health_check_interval: 30  # segundos
  alert_cooldown: 300  # segundos

# Configuración de métricas
metrics:
  enabled: true
  collection_interval: 60  # segundos
  retention_days: 30
  export_interval: 30  # segundos
  
  prometheus:
    enabled: true
    port: 8003
    path: "/metrics"
    timeout: 10
  
  grafana:
    enabled: false
    port: 3000
    dashboards: []

# Configuración de alertas
alerts:
  enabled: true
  channels:
    - "telegram"
    - "console"
  
  events:
    - "command_executed"
    - "error_occurred"
    - "trading_started"
    - "trading_stopped"
    - "large_loss"
    - "daily_limit_reached"
    - "agent_error"
    - "data_issue"
    - "system_health"
  
  thresholds:
    large_loss: 1000  # USD
    daily_limit: 0.05  # 5%
    memory_usage: 0.8  # 80%
    cpu_usage: 0.8  # 80%
    latency: 1000  # ms

# Configuración de Telegram
telegram:
  enabled: true
  bot_token: "${TELEGRAM_BOT_TOKEN}"
  chat_id: "${TELEGRAM_CHAT_ID}"
  rate_limit: 30
  timeout: 10
  retry_attempts: 3
  parse_mode: "HTML"
  use_emojis: true
  
  alerts:
    training_update_interval: 60
    trading_update_interval: 30
    error_notifications: true
    status_reports: true

# Configuración de consola
console:
  enabled: true
  level: "INFO"
  colored: true
  show_timestamps: true
  show_module: true

# Configuración de archivos de log
file_logging:
  enabled: true
  level: "INFO"
  path: "core/logs/monitoring.log"
  max_size: "10MB"
  backup_count: 5
  rotation: "daily"

# Configuración de salud del sistema
health_monitoring:
  enabled: true
  check_interval: 30  # segundos
  
  metrics:
    cpu_usage: true
    memory_usage: true
    disk_usage: true
    network_latency: true
    database_connectivity: true
    api_connectivity: true
  
  thresholds:
    cpu_warning: 70  # %
    cpu_critical: 90  # %
    memory_warning: 80  # %
    memory_critical: 95  # %
    disk_warning: 85  # %
    disk_critical: 95  # %
    latency_warning: 500  # ms
    latency_critical: 1000  # ms

# Configuración de reportes
reports:
  enabled: true
  
  daily_summary:
    enabled: true
    time: "23:00"
    include_metrics: true
    include_trades: true
    include_errors: true
  
  weekly_analysis:
    enabled: true
    day: "sunday"
    time: "22:00"
    include_performance: true
    include_risk_analysis: true
  
  model_performance_report:
    enabled: true
    frequency: "daily"
    include_accuracy: true
    include_predictions: true

# Configuración de dashboards
dashboards:
  enabled: false
  port: 8050
  auto_refresh_seconds: 5
  show_detailed_metrics: true
  show_model_predictions: true
  auto_open: false

# Configuración de notificaciones
notifications:
  enabled: true
  
  email:
    enabled: false
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    username: "${EMAIL_USERNAME}"
    password: "${EMAIL_PASSWORD}"
    from_email: "trading-bot@example.com"
    to_emails: ["admin@example.com"]
  
  webhook:
    enabled: false
    url: "${WEBHOOK_URL}"
    timeout: 10
    retry_attempts: 3
