# Ruta: config/security_config.yaml
# security_config.yaml - Configuración de seguridad enterprise
# Ubicación: config/security_config.yaml

version: "1.0"

# Configuración de encriptación
encryption:
  enabled: true
  algorithm: "AES-256-GCM"
  key_storage: "environment"  # environment, vault
  environment_vars:
    - "ENCRYPTION_KEY"
    - "API_KEY_ENCRYPTION_KEY"
    - "DATABASE_ENCRYPTION_KEY"
    
  # Configuración de claves
  key_rotation:
    enabled: true
    rotation_interval: "90 days"
    key_length: 256
    
  # Configuración de Vault (si se usa)
  vault:
    enabled: false
    url: "http://localhost:8200"
    token: ""  # Configurar en .env
    mount_point: "secret"
    path: "trading_bot"

# Configuración de autorización
authorization:
  enabled: true
  
  # Chat IDs autorizados para Telegram
  authorized_chat_ids: []  # Lista de chat IDs autorizados
  
  # Configuración de rate limiting
  rate_limiting:
    enabled: true
    max_requests_per_minute: 20
    max_requests_per_hour: 100
    block_duration: 300  # seconds
    whitelist: []  # IPs o chat IDs exentos
    
  # Configuración de comandos
  command_timeout: 60  # seconds
  max_command_duration: 300  # seconds
  require_confirmation: true
  confirmation_timeout: 30  # seconds

# Configuración de auditoría
audit:
  enabled: true
  log_all_commands: true
  events:
    - "login"
    - "logout"
    - "trade_executed"
    - "trade_cancelled"
    - "position_opened"
    - "position_closed"
    - "config_changed"
    - "risk_limit_exceeded"
    - "anomaly_detected"
    - "data_access"
    - "system_error"
    - "security_violation"
    
  # Configuración de logs de auditoría
  log_format: "%(asctime)s - AUDIT - %(levelname)s - %(message)s"
  log_file: "logs/audit.log"
  retention_days: 2555  # 7 años para compliance
  
  # Configuración de eventos críticos
  critical_events:
    - "security_violation"
    - "unauthorized_access"
    - "data_breach"
    - "system_compromise"
    
  # Notificaciones de auditoría
  notifications:
    telegram: true
    email: false
    webhook: false

# Configuración de cumplimiento
compliance:
  mifid2_enabled: true
  gdpr_enabled: true
  data_retention_years: 7
  audit_logging: true
  
  # Configuración de MiFID II
  mifid2:
    transaction_reporting: true
    best_execution: true
    client_categorization: true
    product_governance: true
    
  # Configuración de GDPR
  gdpr:
    data_minimization: true
    purpose_limitation: true
    storage_limitation: true
    data_portability: true
    right_to_erasure: true
    
  # Configuración de retención de datos
  data_retention:
    trading_data: "7 years"
    audit_logs: "7 years"
    personal_data: "3 years"
    system_logs: "1 year"

# Configuración de validación de datos
data_validation:
  enabled: true
  schema_validation: true
  range_checks: true
  anomaly_detection: true
  
  # Configuración de validación
  validation_rules:
    price_range:
      min: 0.000001
      max: 1000000
      
    volume_range:
      min: 0
      max: 1000000000
      
    leverage_range:
      min: 1
      max: 125
      
    confidence_range:
      min: 0.0
      max: 1.0
      
  # Configuración de detección de anomalías
  anomaly_detection:
    enabled: true
    threshold: 3.0  # desviaciones estándar
    window_size: 100
    methods: ["statistical", "machine_learning"]

# Configuración de alertas de seguridad
security_alerts:
  enabled: true
  
  # Canales de alerta
  channels:
    telegram:
      enabled: true
      priority: "high"
      
    email:
      enabled: false
      priority: "medium"
      
    webhook:
      enabled: false
      url: ""
      priority: "low"
      
  # Eventos de alerta
  events:
    unauthorized_access:
      enabled: true
      threshold: 1
      cooldown: 300  # seconds
      
    rate_limit_exceeded:
      enabled: true
      threshold: 10
      cooldown: 60
      
    suspicious_activity:
      enabled: true
      threshold: 5
      cooldown: 180
      
    data_breach:
      enabled: true
      threshold: 1
      cooldown: 0
      
    system_compromise:
      enabled: true
      threshold: 1
      cooldown: 0

# Configuración de monitoreo de seguridad
security_monitoring:
  enabled: true
  
  # Métricas de seguridad
  metrics:
    - "failed_login_attempts"
    - "unauthorized_access_attempts"
    - "rate_limit_hits"
    - "suspicious_commands"
    - "data_access_violations"
    - "encryption_failures"
    
  # Configuración de monitoreo
  monitoring:
    real_time: true
    alert_threshold: 5
    cooldown_period: 300  # seconds
    
  # Configuración de reportes
  reporting:
    daily_summary: true
    weekly_report: true
    monthly_audit: true
    incident_report: true

# Configuración de sesiones
sessions:
  enabled: true
  timeout: 3600  # seconds
  max_concurrent: 10
  session_encryption: true
  
  # Configuración de cookies
  cookies:
    secure: true
    http_only: true
    same_site: "strict"
    max_age: 3600  # seconds
    
  # Configuración de tokens
  tokens:
    jwt_enabled: false
    token_expiry: 3600  # seconds
    refresh_token_expiry: 86400  # seconds

# Configuración de red
network:
  timeout: 30  # seconds
  retry_attempts: 3
  retry_delay: 1  # seconds
  max_connections: 10
  
  # Configuración de SSL/TLS
  ssl:
    enabled: true
    verify_certificates: true
    min_version: "TLSv1.2"
    
  # Configuración de firewall
  firewall:
    enabled: false
    allowed_ips: []
    blocked_ips: []
    rate_limit: 100  # requests per minute