# Configuración de Seguridad - Bot Trading v10 Enterprise
# =======================================================

# Configuración general de seguridad
security:
  enabled: true
  encryption_enabled: true
  audit_logging: true
  compliance_mode: true

# Configuración de encriptación
encryption:
  algorithm: "AES-256-GCM"
  key_rotation_days: 30
  key_storage: "environment"  # environment, file, vault
  
  # Variables de entorno para claves
  environment_vars:
    encryption_key: "ENCRYPTION_KEY"
    api_key_encryption: "API_KEY_ENCRYPTION_KEY"

# Configuración de autorización
authorization:
  enabled: true
  
  # Chat IDs autorizados para Telegram
  authorized_chat_ids:
    - "937027893"
  
  # Rate limiting
  rate_limiting:
    enabled: true
    max_requests_per_minute: 30
    burst_limit: 10
    window_size: 60  # segundos
  
  # Timeout de comandos
  command_timeout: 60  # segundos
  max_concurrent_commands: 5

# Configuración de auditoría
audit:
  enabled: true
  log_all_commands: true
  log_all_actions: true
  retention_days: 30
  
  # Eventos a auditar
  events:
    - "command_executed"
    - "trading_action"
    - "configuration_change"
    - "error_occurred"
    - "security_violation"
    - "data_access"
    - "model_update"
  
  # Formato de logs de auditoría
  log_format: "json"
  include_user_info: true
  include_ip_address: true
  include_timestamp: true

# Configuración de cumplimiento
compliance:
  mifid2_enabled: true
  gdpr_enabled: true
  data_retention_years: 7
  immutable_logs: true
  
  # Configuración de reportes de cumplimiento
  reporting:
    enabled: true
    frequency: "daily"
    include_trade_data: true
    include_risk_metrics: true
    include_audit_trail: true

# Configuración de validación de datos
data_validation:
  enabled: true
  
  # Validación de entrada
  input_validation:
    enabled: true
    max_string_length: 1000
    allowed_characters: "a-zA-Z0-9._-@"
    sanitize_input: true
  
  # Validación de comandos
  command_validation:
    enabled: true
    allowed_commands: [
      "start", "help", "status", "metrics", "positions", "balance",
      "health", "train_hist", "train_live", "start_trading", "stop_trading",
      "emergency_stop", "settings", "verify_historical_data",
      "download_historical_data", "historical_data_report"
    ]
    max_arguments: 10
    argument_validation: true

# Configuración de logging de seguridad
security_logging:
  enabled: true
  level: "INFO"
  file: "core/logs/security.log"
  max_size: "10MB"
  backup_count: 10
  
  # Eventos de seguridad a registrar
  events:
    - "authentication_attempt"
    - "authorization_failure"
    - "command_execution"
    - "data_access"
    - "configuration_change"
    - "error_occurred"
    - "security_violation"

# Configuración de alertas de seguridad
security_alerts:
  enabled: true
  
  # Canales de alerta
  channels:
    - "telegram"
    - "console"
    - "log_file"
  
  # Eventos que generan alertas
  events:
    - "unauthorized_access"
    - "rate_limit_exceeded"
    - "command_timeout"
    - "security_violation"
    - "data_breach_attempt"
    - "configuration_tampering"
  
  # Configuración de alertas
  alert_config:
    cooldown_seconds: 300
    max_alerts_per_hour: 10
    escalation_enabled: true

# Configuración de backup de seguridad
security_backup:
  enabled: true
  frequency: "daily"
  retention_days: 30
  encryption: true
  compression: true
  
  # Archivos críticos a respaldar
  critical_files:
    - "config/user_settings.yaml"
    - "config/security_config.yaml"
    - "core/logs/security.log"
    - "core/logs/audit.log"
    - ".env"

# Configuración de monitoreo de seguridad
security_monitoring:
  enabled: true
  
  # Métricas de seguridad
  metrics:
    failed_attempts: true
    successful_commands: true
    rate_limit_hits: true
    security_violations: true
    data_access_patterns: true
  
  # Alertas automáticas
  auto_alerts:
    multiple_failures: true
    unusual_patterns: true
    high_frequency_commands: true
    data_access_anomalies: true
