# Ruta: config/user_settings.yaml
# config/user_settings.yaml
# Ubicación: C:\TradingBot_v10\config\user_settings.yaml
# CONFIGURACIÓN PERSONALIZABLE DEL TRADING BOT
# ============================================

bot_settings:
  name: "TradingBot_v10_Alex"
  trading_mode: "moderate"  # Safer for enterprise, test aggressive in paper mode
  features:
    auto_trading: true
    auto_retraining: true
    risk_management: true
    stop_on_drawdown: true
    adaptive_sizing: true

capital_management:
  initial_balance: 1000.0  # Increased for enterprise realism
  target_balance: 100000.0
  max_risk_per_trade: 5.0  # Reduced for enterprise safety
  max_daily_loss_pct: 10.0  # Tighter for risk control
  max_weekly_loss_pct: 20.0
  max_drawdown_pct: 20.0
  daily_profit_target: 5.0  # More realistic
  take_profit_at_target: false

trading:
  mode: "paper_trading"
  futures: true
  min_confidence: 0.7  # Increased for quality
  max_trades_per_bar: 1
  commission_rate: 0.001
  circuit_breaker_loss: 0.05

risk_management:
  max_risk_per_trade: 0.01  # Tighter for enterprise
  max_daily_loss_pct: 0.05
  max_drawdown_pct: 0.15
  min_leverage: 10.0
  max_leverage: 50.0  # Reduced for safety
  default_stop_loss_pct: 0.015
  risk_reward_ratio: 2.5

trading_settings:
  primary_symbol: "BTCUSDT"
  timeframes:
    # Timeframes unificados para todo el sistema
    symbols: ["BTCUSDT", "ETHUSDT", "ADAUSDT", "SOLUSDT", "DOGEUSDT", "XRPUSDT"]
    timeframes: ["1m", "5m", "15m", "1h", "4h", "1d"]
    
    # Configuración específica por uso
    primary: "15m"        # Timeframe principal para análisis
    secondary: "5m"       # Timeframe secundario para confirmación
    entry: "1m"           # Timeframe de entrada (más granular)
    trend: "1h"           # Timeframe de tendencia
    position: "4h"        # Timeframe de posición
    daily: "1d"           # Timeframe diario para contexto
    
    # Configuración de alineación temporal
    alignment:
      base_timeframe: "5m"        # Timeframe base para alineación
      tolerance_minutes: 1        # Tolerancia en minutos
      min_coverage: 0.95          # Cobertura mínima requerida
      max_gap_minutes: 60         # Gap máximo permitido
      
    # Timeframes por prioridad
    priority:
      high: ["1m", "5m", "15m"]   # Timeframes de alta frecuencia
      medium: ["1h", "4h"]        # Timeframes de análisis
      low: ["1d"]                 # Timeframes de contexto
      
    # Timeframes para ML
    ml_training: ["1h", "4h", "1d"]    # Timeframes para entrenamiento ML
    ml_prediction: ["5m", "15m"]       # Timeframes para predicción ML
  order_settings:
    preferred_order_type: "limit"
    limit_order_timeout: 5
    use_trailing_stops: true
    trailing_stop_distance: 1.5
  stop_loss:
    method: "adaptive"
    default_pct: 2.0
    min_pct: 0.5
    max_pct: 5.0
  take_profit:
    method: "scaled"
    default_pct: 4.0
    levels:
      - target: 2.0
        close_pct: 33
      - target: 4.0
        close_pct: 50
      - target: 8.0
        close_pct: 100

ai_model_settings:
  confidence:
    min_confidence_to_trade: 75.0
    high_confidence_threshold: 85.0
    confidence_adjustments:
      low_confidence: 0.5
      high_confidence: 1.5
  retraining:
    frequency: "adaptive"
    min_trades_before_retrain: 50
    retrain_on_poor_performance: true
    performance_threshold: 60.0
  rewards_config: "src/core/config/rewards.yaml"
  feature_importance:
    price_action: 0.3
    technical_indicators: 0.4
    volume_analysis: 0.2
    market_sentiment: 0.1

reward_system:
  tiers:
    pos:
      - [0, 5, 0.2]
      - [6, 15, 0.5]
      - [16, 40, 1.0]
      - [41, 60, 1.5]
      - [60, 99, 2.5]
      - [100, 1e9, 5.0]
    neg:
      - [0, 5, -0.5]
      - [6, 15, -1.0]
      - [16, 40, -1.5]
      - [41, 60, -3.0]
      - [60, 99, -5.0]
  r_multiple_tiers:
    pos:
      - [0.0, 1.0, 0.1]
      - [1.0, 2.0, 0.3]
      - [2.0, 3.0, 0.5]
      - [3.0, 5.0, 1.0]
      - [5.0, 1e9, 2.0]
    neg:
      - [0.0, 1.0, -0.2]
      - [1.0, 2.0, -0.5]
      - [2.0, 3.0, -1.0]
      - [3.0, 1e9, -2.0]
  leverage_rewards:
    high_leverage_bonus:
      enabled: true
      min_leverage: 5.0
      reward_per_leverage: 0.1
      max_bonus: 2.0
    high_leverage_penalty:
      enabled: true
      min_leverage: 5.0
      penalty_per_leverage: 0.2
      max_penalty: 3.0
    conservative_bonus:
      enabled: true
      max_leverage: 3.0
      consistency_bonus: 0.05
  sl_tp_hits:
    sl_hit_penalty:
      enabled: true
      penalty_amount: -5.0
      scale_with_loss: true
      max_penalty: -20.0
    tp_hit_reward:
      enabled: true
      reward_amount: 5.0
      scale_with_profit: true
      max_reward: 50.0
      leverage_bonus: true
  overtrading_penalty:
    enabled: true
    window_bars: 200
    trade_threshold: 5
    penalty: 0.1
  time_efficiency:
    enabled: true
    weight: 0.1
    per_bar_cap: 0.03
    per_trade_cap: 0.3
  clipping:
    per_step: [-0.2, 0.2]
    per_close_event: [-1.0, 1.5]
  weights:
    r_multiple: 0.3
    risk_efficiency: 0.2
    trade_cost: -0.001
    survival_bonus: 0.001
    progress_bonus: 0.1
    compound_bonus: 0.05

monitoring:
  dashboard:
    enabled: true
    host: "127.0.0.1"
    port: 8050
    auto_open: true  # Enable for your requirement
    auto_refresh_seconds: 5  # Match dashboard requirement
    show_detailed_metrics: true
    show_model_predictions: true
  alerts:
    telegram:  # Added for Telegram integration
      enabled: true
      bot_token: "${TELEGRAM_BOT_TOKEN}"
      chat_id: "${TELEGRAM_CHAT_ID}"
      training_update_interval: 60  # Seconds, for interactive messages
      events:
        - "training_cycle"
        - "large_loss"
        - "daily_limit_reached"
        - "system_error"
        - "high_profit"
    email_alerts:
      enabled: false
      events:
        - "large_loss"
        - "daily_limit_reached"
        - "system_error"
        - "high_profit"
    console_alerts:
      enabled: true
      events:
        - "trade_executed"
        - "model_retrained"
        - "risk_limit_hit"
        - "api_error"
  reporting:
    daily_summary: true
    weekly_analysis: true
    model_performance_report: true

advanced_settings:
  backtesting:
    lookback_days: 365
    walk_forward_months: 3
    min_trades_for_validation: 100
  api_settings:
    request_timeout: 10  # Reduced for HFT
    max_retries: 3
    rate_limit_buffer: 0.8
  data_management:
    cleanup_old_data_days: 90
    backup_frequency_hours: 24
    compress_old_logs: true

multi_symbol_settings:
  enabled: true
  symbols:
    BTCUSDT:
      enabled: true
      allocation_pct: 25.0
      risk_multiplier: 1.0
      leverage: auto
      priority: 1
      max_position_size_usd: 5000
      min_position_size_usd: 100
      volatility_tier: "high"
    ETHUSDT:
      enabled: true
      allocation_pct: 25.0
      risk_multiplier: 1.2
      leverage: auto
      priority: 1
      max_position_size_usd: 5000
      min_position_size_usd: 100
      volatility_tier: "high"
    ADAUSDT:
      enabled: true
      allocation_pct: 15.0
      risk_multiplier: 1.5
      leverage: auto
      priority: 2
      max_position_size_usd: 3000
      min_position_size_usd: 50
      volatility_tier: "medium"
    SOLUSDT:
      enabled: true
      allocation_pct: 15.0
      risk_multiplier: 1.4
      leverage: auto
      priority: 2
      max_position_size_usd: 3000
      min_position_size_usd: 50
      volatility_tier: "medium"
    DOGEUSDT:
      enabled: true
      allocation_pct: 10.0
      risk_multiplier: 1.8
      leverage: auto
      priority: 3
      max_position_size_usd: 2000
      min_position_size_usd: 25
      volatility_tier: "high"
    XRPUSDT:
      enabled: true
      allocation_pct: 10.0
      risk_multiplier: 1.7
      leverage: auto
      priority: 3
      max_position_size_usd: 2000
      min_position_size_usd: 25
      volatility_tier: "medium"


enterprise_features:
  real_time_data_collection: true
  futures_trading: true
  compliance_monitoring: true
  risk_management: true
  performance_tracking: true
  audit_logging: true

trading_enterprise:
  futures_trading:
    enabled: true
    leverage:
      min_leverage: 5
      max_leverage: 20  # Reduced for safety
      confidence_based: true
    margin_mode: "isolated"
    funding_rate_check: true
  strategies:
    ml_strategy:
      enabled: true
      confidence_threshold: 70.0  # Increased for quality
      model_type: "lstm_attention"
      weight: 0.4
    momentum_strategy:
      enabled: true
      confidence_threshold: 75.0
      weight: 0.3
    mean_reversion_strategy:
      enabled: true
      confidence_threshold: 80.0
      weight: 0.2
    breakout_strategy:
      enabled: true
      confidence_threshold: 85.0
      weight: 0.1
  order_management:
    default_order_type: "market"
    stop_loss:
      method: "atr_based"
      atr_multiplier: 2.0
    take_profit:
      risk_reward_ratio: 2.0

data_collection:
  real_time:
    enabled: true
    symbols: ["BTCUSDT", "ETHUSDT", "ADAUSDT", "SOLUSDT", "DOGEUSDT", "XRPUSDT"]
    timeframes: ["1m", "5m", "15m", "1h", "4h", "1d"]
    data_types: ["kline", "ticker", "orderbook"]
  historical:
    enabled: true
    years: 1  # Configuración principal para descarga histórica
    symbols: ["BTCUSDT", "ETHUSDT", "ADAUSDT", "SOLUSDT", "DOGEUSDT", "XRPUSDT"]
    timeframes: ["1m", "5m", "15m", "1h", "4h", "1d"]
    align_after_download: true
  
  sync:
    enabled: true
    symbols: ["BTCUSDT", "ETHUSDT", "ADAUSDT", "SOLUSDT", "DOGEUSDT", "XRPUSDT"]
    timeframes: ["1m", "5m", "15m", "1h", "4h", "1d"]
    max_workers: 4  # Número máximo de workers paralelos
    delay_ms: 100  # Delay entre operaciones para evitar conflictos API
    quality_threshold: 80.0  # Umbral mínimo de calidad de sincronización
    enable_metrics: true  # Habilitar métricas avanzadas
    save_results: true  # Guardar resultados en base de datos
    auto_verify_coverage: true  # Verificar automáticamente cobertura al inicio
    min_coverage_days: 365  # Mínimo de días requeridos
    download_missing: true  # Descargar automáticamente datos faltantes
    verification_interval_hours: 24  # Verificar cada 24 horas
    
    # Configuración de alineación temporal
    alignment:
      enabled: true
      base_timeframe: "5m"        # Timeframe base para alineación
      tolerance_minutes: 1        # Tolerancia en minutos
      min_coverage: 0.95          # Cobertura mínima requerida
      max_gap_minutes: 60         # Gap máximo permitido
      auto_align_on_startup: true # Alinear automáticamente al inicio
      
    # Configuración por timeframe
    timeframe_config:
      "1m":
        priority: 1
        buffer_size: 1000
        flush_interval_ms: 60000
        required_for_trading: true
      "5m":
        priority: 1
        buffer_size: 200
        flush_interval_ms: 300000
        required_for_trading: true
        base_for_alignment: true
      "15m":
        priority: 2
        buffer_size: 100
        flush_interval_ms: 900000
        required_for_trading: true
      "1h":
        priority: 2
        buffer_size: 24
        flush_interval_ms: 3600000
        required_for_ml: true
      "4h":
        priority: 3
        buffer_size: 6
        flush_interval_ms: 14400000
        required_for_ml: true
      "1d":
        priority: 3
        buffer_size: 1
        flush_interval_ms: 86400000
        required_for_ml: true
    # Nueva configuración de almacenamiento por símbolo
    storage_format: "sqlite"  # sqlite, csv, parquet
    storage_structure: "symbol_based"  # symbol_based, unified
    database_per_symbol: true  # Una DB por símbolo y timeframe
    compression_enabled: true  # Compresión de datos antiguos
    compression_days: 180  # Comprimir datos más antiguos que 30 días
  storage:
    timescaledb_enabled: false  # Deshabilitado para usar SQLite por símbolo
    redis_cache_enabled: true
    parquet_files: false  # Usar SQLite en su lugar
    retention_days: 365
    # Configuración de migración
    migration:
      enabled: true  # Migrar datos del sistema legacy
      auto_migrate: true  # Migración automática al inicio
      backup_legacy: true  # Hacer backup del sistema legacy

security:
  encryption:
    enabled: true
    algorithm: "AES-256-GCM"
    key_rotation_days: 30
  compliance:
    mifid2_enabled: true
    gdpr_enabled: true
    data_retention_years: 7
    audit_logging: true
    immutable_logs: true

monitoring_enterprise:
  prometheus:
    enabled: true
    port: 8003
    metrics_path: "/metrics"
  grafana:
    enabled: true
    port: 3000
    dashboards:
      - "trading_dashboard"
      - "risk_dashboard"
      - "pnl_dashboard"
      - "positions_dashboard"
  alerting:
    enabled: true
    channels:
      - "telegram"  # Updated to match alerts
      - "email"
      - "slack"
      - "webhook"

analysis:
  enabled: true
  auto_analysis_interval: 3600
  min_trades_for_analysis: 10
  analysis_lookback_days: 30

dashboard:
  enabled: true  # Added to ensure dashboard_app.py
  enhanced_charts: true
  default_timeframe: "30d"
  auto_refresh_interval: 5
  show_recommendations: true
  max_recommendations: 5

auto_optimization:
  enabled: false
  confidence_threshold_adjustment: true
  position_size_adjustment: true
  stop_loss_adjustment: true

kafka:  # Added for kafka_producer.py and kafka_consumer.py
  bootstrap_servers: "localhost:9092"
  topics:
    market_ticks: "market_ticks"
    processed_data: "processed_data"
    alerts: "alerts"
  producer:
    batch_size: 16384
    linger_ms: 5
  consumer:
    group_id: "trading_bot_consumer"