# Configuración personal del usuario (override opcional)

bot_settings:
  name: "TradingBot_v10_Alex"

# REFERENCIAS, no duplicación
active_symbol_groups: ["primary"]
active_timeframes: ["real_time", "analysis"]
reward_profile: "aggressive"


