# prometheus.yml - Configuración de Prometheus
# Ubicación: C:\TradingBot_v10\monitoring\prometheus\prometheus.yml

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'trading-bot-enterprise'
    environment: 'development'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Trading Bot Principal
  - job_name: 'trading-bot-main'
    static_configs:
      - targets: ['host.docker.internal:8000']
    scrape_interval: 5s
    metrics_path: '/metrics'
    scrape_timeout: 10s

  # Trading Bot Data Collection
  - job_name: 'trading-bot-data-collection'
    static_configs:
      - targets: ['host.docker.internal:8001']
    scrape_interval: 10s
    metrics_path: '/metrics'
    scrape_timeout: 10s

  # Trading Bot ML Training
  - job_name: 'trading-bot-ml-training'
    static_configs:
      - targets: ['host.docker.internal:8002']
    scrape_interval: 15s
    metrics_path: '/metrics'
    scrape_timeout: 10s

  # Trading Bot Trading Engine
  - job_name: 'trading-bot-trading-engine'
    static_configs:
      - targets: ['host.docker.internal:8003']
    scrape_interval: 5s
    metrics_path: '/metrics'
    scrape_timeout: 10s

  # Kafka
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']
    scrape_interval: 15s
    scrape_timeout: 10s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s
    scrape_timeout: 10s

  # Node Exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    scrape_timeout: 10s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
    scrape_timeout: 10s
